### ISSUE TITLE
How to get connection string of developer portal to access the built in storage account of APIM.

### ISSUE THREAD

**Issue by shashiguru** [Azure/api-management-developer-portal#1004]
## Bug description
Hi there, Earlier we used to get the connection string of APIM from **tenant/settings?api-version=2018-01-01** and this REST API got deprecated recently. we dont have any other thing that help us to access the storage account of APIM. Sometimes publish is not creating all the static files in websites container of storage account. is there any way we can access the storage account without connection string?

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
Hi @shashiguru, there is a new operation that was introduced to replace it at the same time we depreciated `tenant/settings`:
`POST /portalSettings/mediaContent/listSecrets`.

This operation returns a temporary storage SAS URL.

The new [set of scripts](https://github.com/Azure/api-management-developer-portal/tree/master/scripts.v2) use the same operation, you can either use them or take them as a reference.

**Comment by shashiguru** [comment]
Correct @azaslonov but it will give us SAS URL for media container. Sometimes publish(operation) won't generate static file in websites container so we wanted to check that the static files are generated or not. For that we need something to access website container.

**Comment by azaslonov** [comment]
I see. That will not be possible anymore, it's now considered a service internal resource.

Every published portal resource is publicly accessible, and if you cannot access it by permalink (which you can define for each media), it means there is probably a bug in the publisher (from this point, since this is a managed version, we'll investigate and fix it), so please send us details (service name, name of the file that is being skipped).
