### ISSUE TITLE
Scripts.v2 migrate the managed developer portal content to other environment not working

### ISSUE THREAD

**Issue by Manojc27** [Azure/api-management-developer-portal#1008]
after NPM install, navigated to Scripts.v2 and ran the below command

node migrate --sourceEndpoint from.management.azure-api.net --destEndpoint to.management.azure-api.net --publishEndpoint to.developer.azure-api.net --sourceToken "SharedAccessSignature integration&2020..." --destToken "SharedAccessSignature integration&2020..."

![image](https://user-images.githubusercontent.com/50986814/97636656-73167900-1a5f-11eb-9ed7-0a7e3bdf8939.png)

It shows some warning and Done. When I navigate to the destination portal nothing changed.

It was worked 5 months before.

If I run the cmd using old code, getting below error

![image](https://user-images.githubusercontent.com/50986814/97639565-d5be4380-1a64-11eb-82b8-3fed5111f03d.png)

**Comment by azaslonov** [comment]
@Manojc27, you don't see changes even in the designer?

**Comment by esarmientoe** [comment]
Same problem here, we don't see the changes on the designer either... Already tested with different versions of node: 14.9.0 and 12.18.3

**Comment by azaslonov** [comment]
@esarmientoe, can you please try to open the designer in another browser. Also, try to open F12 console, type localStorage.clear() and refresh the page.

**Comment by esarmientoe** [comment]
> @esarmientoe, can you please try to open the designer in another browser. Also, try to open F12 console, type localStorage.clear() and refresh the page.

That helped, most of the changes appeared, and after publishing from the designer the changes were reflected on the portal. However, the media changes were not copied over, for example the main logo is empty (instead of showing contoso or our logo).

**Comment by SharpLava** [comment]
Got the same issue, ran the script yesterday. After doing a localStorage.clear() the new content was shown in the admin portal. But having the same issue as @esarmientoe , all my images are not shown. Other media files such as documents were carried over successfully, looks to be just images. Below is what my console gives me when trying to load the new page with those images:
![image](https://user-images.githubusercontent.com/73972238/98873029-be06a680-24cb-11eb-990a-ecf8db0f5a50.png)

**Comment by azaslonov** [comment]
@SharpLava are we talking about managed or self-hosted portal?

**Comment by SharpLava** [comment]
> @SharpLava are we talking about managed or self-hosted portal?

It is managed

**Comment by azaslonov** [comment]
Ok, tomorrow morning the last batch of public cloud will be updated, I'm sure your service is one of them. Just in case can you tell the region you're service in?

**Comment by SharpLava** [comment]
> Ok, tomorrow morning the last batch of public cloud will be updated, I'm sure your service is one of them. Just in case can you tell the region you're service in?

Australia East

**Comment by azaslonov** [comment]
Yep, Australia East is scheduled for tomorrow.

**Comment by AnRei123** [comment]
**Since Tuesday a week ago, we are not able to upload the data.json and media files anymore** to our managed portal environments anymore. We only tested for environments in West Europe until now. 

When invoking the generate.js file, we get the following cmd logging:

(node:165272) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
Error: options.blobHTTPHeaders.blobContentType with value "false" must be of type string.
    at serializeBasicTypes (C:\Users\...\Documents\api-management-developer-portal-2.2.2\scripts\node_modules\@azure\core-http\dist\index.js:819:23)
    at Serializer.serialize (C:\Users\...\Documents\api-management-developer-portal-2.2.2\scripts\node_modules\@azure\core-http\dist\index.js:616:27)
    at getOperationArgumentValueFromParameterPath (C:\Users\..\Documents\api-management-developer-portal-2.2.2\scripts\node_modules\@azure\core-http\dist\index.js:5003:24)
    at getOperationArgumentValueFromParameter (C:\Users\....\Documents\api-management-developer-portal-2.2.2\scripts\node_modules\@azure\core-http\dist\index.js:4974:12)
    at StorageClientContext.<anonymous> (C:\Users\...\Documents\api-management-developer-portal-2.2.2\scripts\node_modules\@azure\core-http\dist\index.js:4722:47)
    at step (C:\Users\...\Documents\api-management-developer-portal-2.2.2\scripts\node_modules\tslib\tslib.js:140:27)
    at Object.next (C:\Users\...\Documents\api-management-developer-portal-2.2.2\scripts\node_modules\tslib\tslib.js:121:57)
    at C:\Users\haesanwo\Documents\api-management-developer-portal-2.2.2\scripts\node_modules\tslib\tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Users\...\Documents\api-management-developer-portal-2.2.2\scripts\node_modules\tslib\tslib.js:110:16)

To fix the issue, I updated already the required npm modules and also tried with the latest version (scripts_v2) of the generate.js and utils.js files. Nothing helped.

I need to deploy portal changes by tomorrow to other environments. Please help to fix this issue by tomorrow. 

(Remark: The cleanup and the capture scripts are still working)

**Comment by azaslonov** [comment]
@AnRei123, I sent you a request for additional information offline.

**Comment by azaslonov** [comment]
@esarmientoe you should be good now. Can you please confirm?

**Comment by azaslonov** [comment]
@Manojc27, answering your original question, those warnings are because of this setting `process.env.NODE_TLS_REJECT_UNAUTHORIZED = 0;`, I'll remove it in the next release because the management endpoint always works through HTTPS.

Regarding the changes, as I mentioned earlier, if you work locally, you can try to reset localStorage with `localStorage.clear()` command. We'll do some changes to make caching less aggressive and maybe detect if the database is ahead of local storage.

Closing the issue for now. Please feel free to re-open shall you need further assistance.

**Comment by AnRei123** [comment]
Hi Alex

Thank you very much for this tip. Yes, I use the scripts locally, but now it works again. I was able to upload the data and media to our test environments! 😊

@Benjamin: can you test on Monday when you are back again if it is also working for you?

Regards,
Angelika
