### ISSUE TITLE
New Developer portal redirecting to incorrect page after OAuth signin.

### ISSUE THREAD

**Issue by kaylakirzinger** [Azure/api-management-developer-portal#1015]
I am trying to set up OAuth for the developer portal on a managed APIM instance. We do not create public APIs so I don't have any need for any type of subscription or sign up functionality. As such I have only a sign-in button to authenticate users.

I have gone through the tutorial step by step. I have the redirect URI's configured as per the tutorial on my app registrations. When i go to use the signin, it gives me a 404 saying "page doesn't exist". it's trying to redirect to https://{amsinstance}.developer.azure-api.net/signup-oauth#provider=Aad&token={token}. I cannot find a single place in my config that has any mention whatsoever of "signup-oauth" as a redirect URL.

My questions:

How and why is it trying to redirect to that page? see my redirect pics below. 
How can I make it stop doing that? I have no need for a signin page, just need to authenticate users on my domain.

You can see the following in the attached pictures:

1) the reply URLs in the APIM instance
2) The reply URLs in the ams server app - 
3) the reply URL that is coming when authenticating - note that it DOES NOT have the /signup-oauth 

![OAuth3](https://user-images.githubusercontent.com/49795114/97921643-d551d100-1d20-11eb-9008-3da8338df02b.png)
![OAuth2](https://user-images.githubusercontent.com/49795114/97921647-d682fe00-1d20-11eb-8f09-5a5c969b1451.png)
![OAuth1](https://user-images.githubusercontent.com/49795114/97921649-d682fe00-1d20-11eb-85b1-09d71edb423a.png)

**Comment by azaslonov** [comment]
Hi Kayla, the redirect like you mentioned `https://{amsinstance}.developer.azure-api.net/signup-oauth#provider=Aad&token={token}.` is done by this widget only (just like you mentioned, you added it):

![image](https://user-images.githubusercontent.com/2320302/98184452-4b8c3a00-1ebf-11eb-811e-723f49ec19f9.png)

As I understand, you're trying to set up sign-in with AAD, and not OAuth authentication for Test console. It means that you need "Identities" section in Azure portal, rather than "OAuth 2.0":

![image](https://user-images.githubusercontent.com/2320302/98184723-ea189b00-1ebf-11eb-8181-9dcb8578a5a0.png)

Redirect to `/signup-oauth` happens only when there is not enough information provided in AAD id_token claims. Specifically, it needs `email`, `given_name` and `family_name`. You can control that in your AAD application.

Hope that helps. Feel free to re-open the issue shall you need further assistance.
