### ISSUE TITLE
Ability to embed HTML/JS on non-self hosted dev portal

### ISSUE THREAD

**Issue by kaylakirzinger** [Azure/api-management-developer-portal#102]
I'd like to embed certain items such as a "Run in postman" button for our postman collection but I am not sure how one would go about doing that when the portal is not self hosted. Is it possible?

**Comment by mikebudzynski** [comment]
@kaylakirzinger 

Currently we don't have plans to provide it in the managed version of the portal. In order to introduce this feature, you'd need to create a new widget through editing the code and self-hosting the portal.

Widgets are documented in detail on the Paperbits website: https://paperbits.io/wiki/widget-anatomy

Also, we're open to community contributions. If you implement the widget - we'd be happy to consider including it in the managed version of the portal.
