### ISSUE TITLE
Close icon of tryout console should be floating in operation details page.

### ISSUE THREAD

**Issue by shashiguru** [Azure/api-management-developer-portal#1023]
## Bug description
Hi there, close icon of tryout console is not floating and its fixed to top right corner. if i scrolled bottom of the console then i need to scroll up to top so that i can close the tryout console. if the close icon floating with scroll then we can close the tryout console wherever we want. please include this change if its make sense to you.

## Actual behavior
When scroll is on top:
![image](https://user-images.githubusercontent.com/30490543/98351181-60450b00-2042-11eb-99eb-e84742d8af27.png)

When scroll on middle or bottom of the page:
![image](https://user-images.githubusercontent.com/30490543/98351299-85d21480-2042-11eb-87f2-d842b93af5ab.png)

## Expected behavior
When scroll is on top:
![image](https://user-images.githubusercontent.com/30490543/98351422-aa2df100-2042-11eb-898f-6732dbdf785f.png)

When scroll on middle or bottom of the page:
![image](https://user-images.githubusercontent.com/30490543/98350970-11977100-2042-11eb-8db0-a6b006cc0eb5.png)

## Is your portal managed or self-hosted?

Managed 

Note: Below css may help to fix this.
    position: fixed;
    right: 40px;

**Comment by azaslonov** [comment]
Hi @shashiguru, makes sense, we'll see what we can do.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
