### ISSUE TITLE
Missing the Header value popup menu when filling in the value under tryout

### ISSUE THREAD

**Issue by sarah-h123** [Azure/api-management-developer-portal#1038]
## Bug description
Missing the popup menu when filling in the Header value, this is when you trying out an api

In the developer portal when trying out an api, you can add header value 
Example from new dev portal without the menu to choose from:

![image](https://user-images.githubusercontent.com/74613127/99417408-2bff0380-28fa-11eb-9afe-f5a794423ed9.png)

## Expected behavior
Example from Legacy dev portal is the expected bahaviour:
![image](https://user-images.githubusercontent.com/74613127/99417571-5bae0b80-28fa-11eb-9db3-951fc5afd17d.png)

## Reproduction steps

1. Go to the developer portal 
2. Choose an API 
3. tryout

## Is your portal managed or self-hosted?
Managed

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
