### ISSUE TITLE
Page editing carrying over to all pages

### ISSUE THREAD

**Issue by kaylakirzinger** [Azure/api-management-developer-portal#104]
**Describe the bug**
Created a new page. Edited content on new page. It ended up deleting all content on the rest of my pages and turning every page into the page I had edited. See video:
https://www.screencast.com/t/6fYer8mKLD 

**To Reproduce**
1. Create new page
2. Edit content in new page
3. Click existing page
4. Confirm that content of existing pages was overwritten by new pages

**Expected behavior**
Pages edit separately and don't overwrite.

**Screenshots**
Video: https://www.screencast.com/t/6fYer8mKLD

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser - Chrome
 - Version 75

**Comment by azaslonov** [comment]
Hi Kayla, the for the explanation and video. We'll investigate.

**Comment by azaslonov** [comment]
Kayla, could you please copy all the errors from F12 console of your browser when this issue happens?

**Comment by kaylakirzinger** [comment]
There really aren't any errors as I switch from page to page. I got this once:

![image](https://user-images.githubusercontent.com/49795114/60925333-fa3b4e80-a268-11e9-8e8e-519946b6f6f3.png)


Refused to apply style from 'https://ams-dev-scus-core.developer.azure-api.net/styles/customizations.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
gettingstarted:1 Refused to apply style from 'https://ams-dev-scus-core.developer.azure-api.net/styles/theme.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
gettingstarted:1 Refused to apply style from 'https://ams-dev-scus-core.developer.azure-api.net/editors/styles/paperbits.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.


Here is another video:
https://www.screencast.com/t/Rmc0EVofpfpW

**Comment by azaslonov** [comment]
Understood. Those errors that you see most likely not related to your issue. Thanks again for all the information, we'll keep you posted.

**Comment by mikebudzynski** [comment]
@kaylakirzinger We are not able to reproduce the issue. We'll try to root cause the problem through our logs and then we will update you with our findings.

**Comment by kaylakirzinger** [comment]
Thank you! I can share with someone over Teams or something any time, or let me know if there's anything else I can do to assist.

**Comment by mikebudzynski** [comment]
@kaylakirzinger 

The problem with your developer portal is that you added the _Getting started_ page as the _Default_ layout instead.

Layout is a template, which defines how pages are displayed within it and is matched against a URL pattern. In this case, the default layout is matched against `/*`, so any page will use it unless it's overridden by another layout. Also, this _Default_ layout now doesn't have the _Content_ block, which is supposed to display contents of a page. Because of that it's just a static layout that displays the same information regardless of a page it should contain.

You can fix the problem the following way:
1. Go to _Layouts_ and deleting the _Default_ layout.
2. Create a new layout with the URL template `/*`. Make sure the _Content_ block is there.
3. Go to _Pages_ and editing the _Getting started_ page however you wish.

We'll make the menu more descriptive to help avoid such mistakes in future.

Please, let us know if you manage to solve the problem. If you have more feedback, we'd be happy to hear it as well.
