### ISSUE TITLE
Open in new window

### ISSUE THREAD

**Issue by CoumbaNDI** [Azure/api-management-developer-portal#1062]
## Bug description

A clear and concise description of the bug.

## Reproduction steps

1. Go to www.apim.com'
2. Click on the link 'See documentation'
3. Link open on the same web page 

## Expected behavior
1. Go to www.apim.com'
2. Click on the link 'See documentation'
4. Link open in different web page

## Is your portal managed or self-hosted?

Managed 

![image](https://user-images.githubusercontent.com/52564104/100634271-5eafef80-332f-11eb-96a5-0b96c52da9f0.png)

Everytime I modify the option on a new window, after saving and publishing. It still won't work !

**Comment by ilspiert** [comment]
Can confirm that - this issue is back. Just tested it on my managed instance: The "new windows" option is never shown correctly in Design mode. Even it is not shown in Design mode, the "new window" thing does work for Navigation itemes but NOT for Text links and Image links.
Looking forward for a bugfix :)
P.S. Had that issue with latest Edge and Chrome browsers.

**Comment by azaslonov** [comment]
Thanks guys, working on it.

**Comment by coskun** [comment]
Any updates about this ?

**Comment by azaslonov** [comment]
Fixed all cases. Managed version release is in progress.
