### ISSUE TITLE
Publishing Issues - Help needed

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1083]
## Bug description

We are currently experiencing some issues with the publishing step. It differs from user to user. For example I can publish in the DevPortal itself and sometimes (not always - somewhat inconsistent) in the Azure Portal but never with the scripts. My colleague @AnRei123 cannot publish at all. We are unsure what to do. If a restart of the DevPortal instances is needed or if we cannot do anything right now and for example some services are currently overloaded.

## Reproduction steps

1. Make changes in the DevPortal
2. Try each way to publish (Scripts - Azure Portal - DevPortal)
3. Check if the changes got published

## Is your portal managed or self-hosted?

Managed

**Comment by ZarTrox** [comment]
I read in another Issue #1081 , that apparently there are caching Issues. Could this also be a symptom of this Problem?

Thanks in advance.

**Comment by AnRei123** [comment]
Don´t know. I tried to several time to clear the cache before and after publishing. Also for a different APIM instance. Also opened the published version in incognito mode of the Chrome browser. Nothing helped. The updated content is still not shown. Please help. Since yesterday, we only try to fix issues and test how to deploy and publish. We have currently deadlines and I feel little desperate now.

**Comment by azaslonov** [comment]
Hi folks, let me check your services.

**Comment by azaslonov** [comment]
@AnRei123, I sent you an email with questions.
@ZarTrox, can you please send your service name to apimportalfeedback@microsoft.com (could not find your records).

**Comment by ZarTrox** [comment]
Hi azaslonov, I'm affiliated with AnRei123 and have the same services

**Comment by azaslonov** [comment]
Ok, thanks. We have started an email thread already, so I'm closing this issue for now.
