### ISSUE TITLE
bootstrap cdn is not included while application is running in server

### ISSUE THREAD

**Issue by Vinoth-44** [Azure/api-management-developer-portal#1110]
## Bug description

Bootstrap CDN library is added in local while we add cdn link in page.html (src\themes\website\assets\page.html) But when we deploy the same code in DEV server, Bootstrap CDN library is not loaded in sources.

## Reproduction steps

1. Go to page.html
2. Add bootstrap CDN links in the header
3. bootstrap resources are loading in local
4. But the same is not loading in dev server

## Expected behavior

Bootstrap CDN library should be loaded while application is running in server. This should be worked as is in local

## Is your portal managed or self-hosted?

 Self-hosted

## Release tag or commit SHA (if using self-hosted version)
Latest master code

## API Management service name

[e.g., contoso-api]

## Environment

 - Operating system: Windows
 - Browser: Google Chrome
 - Version: [e.g., 22]

## Additional context

Add any other context about the problem here, including screenshots.

Local:

![localAPIM](https://user-images.githubusercontent.com/35361553/103851301-78cbb300-50cf-11eb-82f5-2b40003791e8.PNG)

Server:

![Dev](https://user-images.githubusercontent.com/35361553/103851626-32c31f00-50d0-11eb-9970-29428fcd7714.PNG)

Local build code (dist/website/)

![builded code](https://user-images.githubusercontent.com/35361553/103851672-4e2e2a00-50d0-11eb-9fe2-c9bf549babaa.PNG)

**Comment by azaslonov** [comment]
Hi @Vinoth-44, yep this is because the template used for publishing is different. Moreover, we're planning to remove page.html template and completely switch to the generation of the document through the number of plugins. In fact, they are already in use for place different artifacts into the page (i.e. JSON-LD structured data).

There is an interface that allows you to inject things into published page:
```ts
export interface HtmlPagePublisherPlugin {
    apply(document: Document, page?: HtmlPage): void;
}
```

So, you can do stuff like this:
```ts
export class MyHtmlPagePublisherPlugin implements HtmlPagePublisherPlugin {
    public async apply(document: Document, page: HtmlPage): Promise<void> {
        const bootstraplLinkElement: HTMLStyleElement = document.createElement("link");
        bootstrapLinkElement.setAttribute("rel", "stylesheet");
        bootstrapLinkElement.setAttribute("type", "text/css");
        bootstrapLinkElement.setAttribute("href", "https://...");
        document.head.appendChild(bootstrapLinkElement);
    }
}
```
Then you'll need to register it in, i.e. `apim.publish.module.ts`:
```ts
injector.bindToCollection("htmlPagePublisherPlugins", MyHtmlPagePublisherPlugin);
```

I feel there needs to be a separate documentation article for this :)

Hope that helps. I'm closing this issue for now, but please feel free to re-open shall you need further assistance.
