### ISSUE TITLE
Disable user sign-up

### ISSUE THREAD

**Issue by mattosaurus** [Azure/api-management-developer-portal#1130]
Hi,

We are using the API Management Portal to allow clients to explore APIs we are hosting for them. These APIs return client specific data and access to the portal is managed by AAD, users are added by us authorising them in AAD and there should be absolutly no option for external users to be able to sign up and access these APIs.

I have managed to disable the sign up functionality in the developer portal which I have documented [here](https://blog.bitscry.com/2019/11/07/disabling-signup-in-the-azure-api-management-developer-portal/) but this is by no means a user friendly process and I don't entirely trust that it's removed all sign up functionality.

Would it be possible to add a "disable sign up" option in the portal to simplify this for the user and to ensure it is all done correctly? I imagine this is quite a common use case as while the developer portal functionality is great for helping clients integrate with APIs it is hard to justify it's use while there's the potantial for external users to sign up and view the clients data.

Thanks

**Comment by jpgough** [comment]
+1, this feature is something we were about to ask for too.

**Comment by mikebudzynski** [comment]
To disable sign-up, you need to remove all identity providers:
![image](https://user-images.githubusercontent.com/40186513/106053147-4e9e5d00-609f-11eb-8782-ecb39b895398.png)

After you do that, you can also remove the sign-up pages from the developer portal (because they won't work).

I'll change this Issue to a documentation item, instead of a feature request.

**Comment by mattosaurus** [comment]
Is this the accepted path to remove sign-up functionality then?

1. Remove identity provider in Azure portal
2. Remove page links and buttons in developer portal
3. Delete pages using the API

As far as I can tell this works but it's not the most intuative process and although offical documentation around it would be good, it feels like this is a relativly common use case that would benifit from a slightly more user friendly option.

**Comment by mikebudzynski** [comment]
>    Remove identity provider in Azure portal
>    Remove page links and buttons in developer portal
>    Delete pages using the API

Yes, that's the process. You can delete the pages in the administrative interface, you don't need to resort to the management API calls.

> As far as I can tell this works but it's not the most intuative process and although offical documentation around it would be good, it feels like this is a relativly common use case that would benifit from a slightly more user friendly option.

I will keep this item open for tracking purposes.

**Comment by ErikMogensen** [comment]
Hi @mikebudzynski,

Two questions, 

1. Is it all right to remove the signin and/or signup pages? On https://docs.microsoft.com/en-us/azure/api-management/api-management-howto-developer-portal-customize#customize-the-portals-content it states:

> Due to integration considerations, the following pages can't be removed or moved under a different URL: /404, /500, /captcha, /change-password, /config.json, /confirm/invitation, /confirm-v2/identities/basic/signup, /confirm-v2/password, /internal-status-0123456789abcdef, /publish, **/signin**, /signin-sso, **/signup**.
 
We removed the signin and signup pages but then we were unable to access the portal so in AAD we added the email claim to the token that the portal gets, thus preventing the user from having to sign up explicitly. That worked for a couple of days but starting at the end of last week, we cannot login in using AAD to that portal anymore. Since it worked for a while the problem with the portal may be due to something else.

If we uncheck "Redirect anonymous users to sign-in page" we are able to access it. However publishing still fails with an error about being unauthorized.

2. If it is all right to remove the signup page, is it a supported way to handle that by adding the email claim to the JWT through changing the AAD app registration?

BTW: We couldn't find a way to remove those pages in the developer portal GUI, but that is a minor issue.

**Comment by PgInsight** [comment]
+1

We have a private API which is an invite only for select customers.

We do not want/need any self sign up as this is in our view a security risk as our product/model does not support self sign up.

**Comment by azaslonov** [comment]
Closing the issue since the documentation with steps provided: https://docs.microsoft.com/en-us/azure/api-management/developer-portal-faq#how-do-i-disable-sign-up-in-the-developer-portal

**Comment by harouny** [comment]
@azaslonov @mikebudzynski I kindly request to re-open this issue and treat this as a feature request. Developer portal should automatically detect when "Username and password" identity is removed from identities and hide all UI elements related to it (as it doesn't work anyway). 
That's a much better user experience than us having to manually remove UI elements as well.
