### ISSUE TITLE
Option to import static html content into APIM Dev Portal

### ISSUE THREAD

**Issue by watson20201** [Azure/api-management-developer-portal#1132]
Is there a way to update static page content for custom pages created in the APIM Dev Portal?
 
An example is we have a custom Terms & Conditions page that was created in the APIM Developer portal.
![image](https://user-images.githubusercontent.com/62035456/106064877-56bdd180-615f-11eb-9f36-52d22fcea398.png)

Now instead of updating the content of this page through the Developer Portal, is there a way to pragmatically update the content either through a PS script or an API?

**Comment by azaslonov** [comment]
Hi @watson20201, yes, to manipulate the content you can use content management API. Please have a look [at this article](https://github.com/Azure/api-management-developer-portal/wiki/Content-management-API).

Please let me know if you need help with that. Since the content is stored in the form of JSON, you may need a tool to convert HTML or Markdown into it, and I can assist you better if you give me a bit more details of your scenario.

**Comment by mikebudzynski** [comment]
The latest API documentation is available at https://docs.microsoft.com/en-us/rest/api/apimanagement/2020-06-01-preview/contenttype/listbyservice

**Comment by azaslonov** [comment]
Closing this one. Let's use #1207 for tracking and collecting the feedback. Seems like we're narrowing down the scenarios we need to support.
