### ISSUE TITLE
Migrate command using script v3 fails for migration of apim developer portal from one subscription to another subscription

### ISSUE THREAD

**Issue by SSanjeevi** [Azure/api-management-developer-portal#1144]
## Bug description

Migrate command using script v3 fails for migration of apim developer portal from one subscription to another subscription. Apim 1 in one subscription A and apim 2 is in subscription B when using script v3 for migrating the portal it fails with following error:

"Unable to complete migration. Unable to complete cleanup. Unable to delete content. Unable to fetch content types. Unauthorized. Make sure you're logged-in with "az login" command before running the script."

## Reproduction steps

1. Create apim 1 in A subscription and apim2 in B subscription
2. use migrate v3 command to migrate from apim1 to apim 2.
3. error at cleaning up "Unable to complete migration. Unable to complete cleanup. Unable to delete content. Unable to fetch content types. Unauthorized. Make sure you're logged-in with "az login" command before running the script."

## Expected behavior

Apim developer portal import should complete.

## Is your portal managed or self-hosted?

both are Managed portals

## Release tag or commit SHA (if using self-hosted version)

Latest version.

## API Management service name

will share in email.

## Environment

NA

## Additional context

Am executing the command in Azure devops task.
Tried using Azure cli task, powershell task it works for apim in same subscription and tenant but fails for different subscription.

<img width="699" alt="apim dev portal migrate command v3 issue" src="https://user-images.githubusercontent.com/24915474/107345414-88cd1d00-6ae9-11eb-9486-a53cae078d02.PNG">

**Comment by SSanjeevi** [comment]
I managed to succeed by using this PR changes.

Where i have added code to login to az cli with each subscription on source and destination.

https://github.com/Azure/api-management-developer-portal/pull/1145

**Comment by SSanjeevi** [comment]
I managed to succeed by  using this PR changes 
https://github.com/Azure/api-management-developer-portal/pull/1145

**Comment by hammdo** [comment]
What permissions are necessary for the service principal in order to perform a clean/delete and import?  Currently, we have:

Register app to create service principal, create secret

add role assignment with APIM READ access DELETE and WRITE access on the app

add the service principal as the contributor in APIM

We're failing with:

Cleaning up...
node : Unable to complete migration. Unable to complete cleanup. Unable to delete content. Unable to fetch content types. Looks like you are not allowed to perform this operation. 
Please check with your administrator.
At F:\projects\Rogue-One\dev-portal\api-management-developer-portal\scripts.v3\DevPortalMigration.ps1:144 char:7
+       node .\migrate --sourceSubscriptionId \`"$sourceSubscriptionId\ ...
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unable to compl... administrator.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

**Comment by Sdelausnay** [comment]
We are using V3 and also have the same issue when we try to copy the Portal to APIMs in different subscriptions. 

We use a AzureCLI taks in depovs pipeline just calling the node migrate function. 

We running the same script on APIM in the same subscription, we don't have the issue. 

We also check and the Service Principles have the same rights on both subscriptions. 

Any other ideas why it would be failing?
