### ISSUE TITLE
Increase publishing speed

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1156]
## Bug description

Currently when trying to publish the Developer Portal the process takes > 10min to finish. If you implement some changes and want to see it from the customer/partner view you need to wait this time, not sure if it even finished yet, and try to see the new changes. This interrupts the workflow 

## Expected behavior

No matter how much content a Portal contains the publishing step should not take more than 2-3min. 1 minute would be even better.

## Is your portal managed or self-hosted?

Managed

## Additional context

When publishing from the Azure Portal the time of the publish gets refreshed. But if you refresh the page the time gets reset (to an older publish time). This can be very confusing.
![image](https://user-images.githubusercontent.com/58420097/108352477-31b10180-71e7-11eb-9ef5-d335aeb06c82.png)
An improvement to that would be another info box next to "last published" which contains information about the current publication-process status. E.g. "publishing", "done", etc. to be able to see when you can access the published portal.

**Comment by azaslonov** [comment]
Hi @ZarTrox,
That is confusing, true. There is a work in progress to address this - portal revisions UI in Azure portal, which allows you to track the progress of your publications, view their history, and switch between them. Of course, it comes with an API endpoint to allow automation.

Publishing speed is another effort that is going on right now, I'm sure we'll see the results pretty soon.

**Comment by ErikMogensen** [comment]
Happy to hear that you are working on this, @azaslonov! How long time does it take before you know that the publishing failed? I am trying to publish it using REST API which does not seem to work (using code from Scrips.v2), and usually not through the Azure portal either. Best seems to be publishing it through the Developer portal itself.

**Comment by azaslonov** [comment]
Hi Erik, the API is not ready yet, publishing still relies on the portal endpoint. In your case, I believe the problem is related to VNET, and a new endpoint will address this issue as well. In the UI, in case of success or failure, the state of the publication will be updated immediately.

**Comment by ErikMogensen** [comment]
I knew that the ARM endpoint that has been commented out in Scripts.**v3** didn't but do you mean that the publish function in Scripts.**v2**\migrate.js does not work? 

Thanks for the tip about VNet, that may explain some of the issues. However, I am also working instances running without any VNet which also have publishing problems.

**Comment by azaslonov** [comment]
The endpoint in v2 scripts should work fine unless it, again, related to VNET somehow. Do you have any errors that it spits out or it returns OK, and the publishing itself fails?

**Comment by ErikMogensen** [comment]
It returns Ok and then nothing happens. I dont know how long to wait though. I have waited up to one hour. 

Is it extra difficult to get the portal to publish the first time after the apim instance has been created?

**Comment by azaslonov** [comment]
I see, so it is something we should look at then. Can you please send me service names?

It's not difficult. I believe you're asking in the context of the backup/restore scenario?

**Comment by ErikMogensen** [comment]
Thanks! I just mailed you. 

I want to pick up saved portal content from disk and put it on an apim intance, modify it and then publish it, all done from inside an azure devops pipeline.

**Comment by AnRei123** [comment]
Since yesterday, I tried to publish again. Publishing does not work anymore for me - at least for two of the environments that I tested to publish - irrespective which option I have chosen to trigger it and irrespective how long I do wait for the results to show up!!! Even so the message occurs that "Publishing has been scheduled" and even so there was no error message indicating that something is wrong or not working! 
I like to rollout changes by today, but this seems not to be possible with the current issue.

**Comment by mikebudzynski** [comment]
@AnRei123 We're investigating the problem.

**Comment by azaslonov** [comment]
@AnRei123, this issue was, again, due to very scarce resources of Developer SKU, I made adjustments to one of your services that reported publishing errors, and launched publishing, which succeeded. We'll see if this results into a hotfix.

Regarding visibility of the publishing process, as I mentioned before, we're releasing a specific UI for this soon.

**Comment by AnRei123** [comment]
Developer SKU should not be a criteria for publishing the content in my opinion. Do you plan to support editing portal content also for Developer SKUs in future? We need the portal content for several instances - with Developer SKU and also for production.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
