### ISSUE TITLE
Add option to disable "Try it" console

### ISSUE THREAD

**Issue by VickiFu** [Azure/api-management-developer-portal#1181]
Our issue is our API encoding image with base64, but the code from try it use different encode

Can we have way to turn try-it console off or change the codebase for it? It doesnt help us with any value.
Below is the result:

HTTP/1.1 400 BAD REQUEST

content-length: 122
content-type: application/json
date: Wed, 10 Mar 2021 15:45:20 GMT
vary: Origin
{
    "message": "Failed to decode JSON object: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte"
}

**Comment by VickiFu** [comment]
@azaslonov Hi Alex, thank you for your help. Because the user (at least me) could assume that with upload images option all encode/decode will be taken care by the system with API need. So I feel console without any customization about how the image submit could confuse clients in some way.
Thanks
Vicky

**Comment by azaslonov** [comment]
@VickiFu. Yes, makes sense. I repurposed this item into a feature request, we'll add this option to disable "Try it" console for managed version.

Just in case, you still can go with the self-hosted portal route if you want to address this issue properly for your users. Unfortunately, we don't be able to add this encoding option into managed version because it is a super-specific case of yours.

**Comment by VickiFu** [comment]
Yes. Thank you for that. we can wait this feature...
