### ISSUE TITLE
Duplicate text fields including formats and hyperlinks (on the same page)

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1199]
## Bug description/expected behavior

Currently to duplicate the content of an existing text field we need to create a new text field with new texts and new formats.
To maintain and edit a lot of content pages, it is essential to efficiently being able to work that duplicating a text field including texts and formats is supported at least for the same page.

Also helpful would be to be able to copy and paste text fields across different pages.

## Is your portal managed or self-hosted?

Managed

**Comment by ZarTrox** [comment]
@AnRei123 fyi

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
