### ISSUE TITLE
Copy-paste string with styles and format

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1200]
## Bug description

When working in the editor mode of the DevPortal to create content we would want to copy a link, a header or any other string which has some form of style or format from one text element to another one on the same page or across pages.

Currently all the style-information is lost upon copying and pasting it.
![CopyTextElementsBug](https://user-images.githubusercontent.com/58420097/112119790-fdea4280-8bbd-11eb-97c8-427e63d17762.gif)

This is extremely annoying when you need to search and set a new link target for a string, especially since it is not displayed that the link target is missing.
![CopyLinkElementsBug](https://user-images.githubusercontent.com/58420097/112121661-c41a3b80-8bbf-11eb-8a2d-2b59af108da3.gif)

Even when copying into the same text-element the information is lost.
It would be a great improvement if one would be able to copy a part of a text-element and simply be able to paste it into the next one.

## Expected behavior

Ideally one should be able to select the string and copy the text with ctrl+c and paste it anywhere in the DevPortal with ctrl+v and all information is transmitted.
If this should not be possible maybe a copy button to manually copy the selected text with the complete styling and formatting should be present. 

## Is your portal managed or self-hosted?

Managed

**Comment by ZarTrox** [comment]
@AnRei123 fyi

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
