### ISSUE TITLE
Styles not applied to widgets

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1203]
## Bug description

Today I encountered the issue that some Menu widgets (vertical) don't have any styling applied to them. Meaning for example that no spaces are left between the lines. Testing issues like this delays working on more pressing topics.

Even after emptying the cache the issue remains.
This issue is prominent in the editor AND the published version of the DevPortal.

## Browser specs

Chrome: Version 89.0.4389.90

**Comment by AnRei123** [comment]
What is going on? Why are all my menu styles and lists on pages messed up since today? And even the image gallery does often not remember anymore if I upload and save new images. I was going to review some topics with SMEs today, but as some texts are also overlapping, you are not able to send the preview around. Tomorrow, I am on vacation. But I need urgently a solution by Monday morning.

**Comment by azaslonov** [comment]
Hi @Angelika, I have rolled back the last release for your services, until we figure out what's happening.
