### ISSUE TITLE
Use Azure Resource manager API instead of APIM Management API

### ISSUE THREAD

**Issue by JulesP96** [Azure/api-management-developer-portal#1217]
Hi, 

Are there any plans to fully utilize the ARM endpoint instead of the APIM Management API?

Instead of using: **https://<apimServiceName>.management.azure-api.net** I'd like to use **https://management.azure.com/**. For the build phase, I can see that the scripts V3 already uses the management.azure.com endpoint, however, when using it in the `config.json` the MapiClient still generate a SharedAccessSignature when calling `yield this.authenticator.getAccessToken()`. 

I find it quite unclear, especially with the method `ensureUrlArmified`. I expected that the URL was "transformed" to use the management.azure.com endpoint, but that is not what the implementation is doing (since it does not uses a subscription id nor a resource group name. 

Maybe, for now, the APIM Management API is mandatory, and maybe that "for now" is more like a "forever". Hence, my question.

**Comment by mikebudzynski** [comment]
> Are there any plans to fully utilize the ARM endpoint instead of the APIM Management API?

Yes, we have plans to:

1. Make the administrative plane of the portal to use ARM instead of direct access API. ETA is several months.
2. Provide support for publishing of the developer portal via ARM (the only remaining piece). ETA is several weeks.

"ARMification" transforms the URL to a specific format that's defined by ARM (i.e., /subscriptions/{guid}/...).
