### ISSUE TITLE
Password length bypass while changing password via forget request

### ISSUE THREAD

**Issue by CosminLazar** [Azure/api-management-developer-portal#1227]
## Bug description

The password length limit can be bypassed while setting a new password through the password reset link. I have set my account password to just 1 nothing else.

## Reproduction steps

1. Go to any developer portal reset password page and request a password reset link.
2. Click on the password reset link. Now you will be asked to set your new password.
3. Enter any 8 digit password initially to make the javascript satisfy.
4. Now click the change button and intercept the request with any proxy tool like burp suite before the request land on the server.
5. Change the password from your dumpy 8 digits to just 1 and forward the request to the server.
6. Now try to login with your email and the new password you set.

## Expected behavior

The password complexity requirements should be uniformly enforced.

## Is your portal managed or self-hosted?

Managed

## API Management service name

apim-bilinfo-prod

## Environment

Environment agnostic

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
