### ISSUE TITLE
Previously requested password reset tokens do not expire

### ISSUE THREAD

**Issue by CosminLazar** [Azure/api-management-developer-portal#1229]
## Bug description

When requesting a password reset multiple times via the developer portal all the reset links are valid. I would expect that only the last generated password reset link would be valid.

## Reproduction steps

1. Go to a developer portal reset password
2. Request Password Reset Token Number 1
3. After sometime Request Token Number 2
4. Then Token Number 3.
5. Check your mail inbox, all three tokens are there
6. Try resetting the password with the first link
7. The link has not expired and it allows you to reset the password

## Expected behavior

Only the last password reset link should be

## Is your portal managed or self-hosted?

Managed

## API Management service name

apim-bilinfo-prod

## Environment

Environment agnostic

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
