### ISSUE TITLE
Session does not expire on password change

### ISSUE THREAD

**Issue by CosminLazar** [Azure/api-management-developer-portal#1230]
## Bug description

When you change the password of your account in the developer portal from one browser or computer , the current remaining session on the other device or browser does not expire.

## Reproduction steps

1. Login from Browser 1.
2. Login from Browser 2.
3. Change password from Browser 1.
4. Now go to Browser 2 and check that session is still active.
5. Session did not expire.

## Expected behavior

All active sessions should be immediately invalidated on password change.

## Is your portal managed or self-hosted?

Managed

## API Management service name

apim-bilinfo-prod

## Environment

Environment agnostic

**Comment by mikebudzynski** [comment]
Related to #1237

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
