### ISSUE TITLE
Responsiveness for images with text

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1245]
## Bug description

Currently the responsiveness in the DevPortal scales images corresponding to the screen resolution. Meaning if I use a tablet or a mobile phone, then the image gets smaller and smaller. While this is desirable for some cases it is not desirable for images containing text. At some point text may not be able to be read.

![TextInImage](https://user-images.githubusercontent.com/58420097/114538285-7e4b1300-9c53-11eb-8b1a-0a909e90f422.gif)

In some scenarios like here an image is not always alone in its "row", therefore does not have the full width of the page available and gets small quickly.

The current workaround to read the text is to open the image in full size. 

## Expected behavior

In the gif it is visible that the text does indeed not get scaled with the size of Browser, consequently staying the same size.
A similar behavior would be good for images with text.

The way to achieve this could be an option to select if an image should be scaled proportionally or keep the readability of the text. Maybe being able to scroll the image and set a minimum size for the image could be useful in some cases.

## Is your portal managed or self-hosted?

Managed 

---
@AnRei123

**Comment by AnRei123** [comment]
In the example above, the image width uses the whole column by default. 

But especially in the case if the inserted images is smaller than the content column outside the image, when reducing the Windows size, the image size should not be reduced proportionally. The image size and proportion should be kept as long as possible even for small window resolutions to allow readability of the texts inside the image.

For images that contain texts like graphics often do, there should be a dedicated setting in the image widget that allows to configure to keep the image size and its proportion even for smaller window resolutions or to offer a scrollbar if the window resolution is too small. If the window gets smaller than the image, the content of the image shall be scrollable in this case. The same behavior should be inherited for the lightbox and the open in a new window view if the Window resolution is too small for this kind of setting in the image widget.

**Comment by azaslonov** [comment]
Ok, I see. It looks like a grid issue rather than a picture. What would help here is to set fixed width for a column containing the picture. There are few things coming up that can help:

The first one is the "Table" widget (a week or so away), which will have min and max width settings for columns and rows, the only problem would be the rows that do not wrap on smaller screens.

The second one (June) is a grid editor, that will allow controlling the grid in full (including wrapping, min/max width/height, etc.)

For now, the only workaround is to modify the content JSON directly, setting up the required parameter for the grid. Let me know if you want to go that route, I can write up something on this topic.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
