### ISSUE TITLE
Losing authentication when opening a link in a new window/tab

### ISSUE THREAD

**Issue by martinsamanek** [Azure/api-management-developer-portal#1250]
## Bug description

Authentication is kept only in the tab, where I was logged in. When opening a link into a new tab/window (use Ctrl+Click), I'm not authenticated in the new tab.

## Reproduction steps

1. Go to Developer portal
2. Click on Sign In 
3. Sign In with an available method (we use the form and AAD)
4. Ctrl+Click on any link (i.e. APIs)
5. Check authentication status in the new tab

## Expected behavior

User is authenticated in the new tab

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

2.8.0

## API Management service name

apimoridev

## Environment

 - Operating system: Windows 10 64bit
 - Browser: Chrome
 - Version: 89.0.4389.114

### Business impact:
We are not able to easily send a link to an endpoint, which is not public. If I'm logged in into the portal and someone sends me a link to the portal, which requires authentication, the link won't work in my browser. Only if I open it in the same tab, where I'm currently logged in. This is a pretty serious issue for communication with our consumers.

**Comment by azaslonov** [comment]
Hi @martinsamanek, since you're using the self-hosted portal (and I believe it's a static type of hosting like blob storage), there is no backend that would process cookies to restore the session. Plus that, looks like the browser doesn't transfer `sessionStorage` content into new tabs.

So, for now, looks like you'll have to live with this, but for the future, we're planning to open-source our backend which you'll be able to host, i.e. in Azure App Service if you'd like, and which will take care of the cookies as well.
