### ISSUE TITLE
Responsiveness of menu-items

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1260]
## Bug description

When resizing the browser window a menu on a side of the page is contrary to the setting not anymore aligned to the top.
One has to scroll to see the menu.

Normal:
![image](https://user-images.githubusercontent.com/58420097/115351970-1ba7c900-a1b7-11eb-8d99-ccbaf12e2757.png)

Buggy:
![image](https://user-images.githubusercontent.com/58420097/115351984-1fd3e680-a1b7-11eb-83dc-e0f17a7d7016.png)

Settings for the menu-widget in the collapsible panel:
![image](https://user-images.githubusercontent.com/58420097/115352533-bef8de00-a1b7-11eb-81bb-47e65243888a.png)

## Expected behavior

As long as there is a column to fit the menu in the menu should be shown according to the settings (here: at the top).

## Is your portal managed or self-hosted?

Managed
---
@AnRei123

**Comment by azaslonov** [comment]
Hi @ZarTrox, I think that you need to do the alignment on the grid cell, not on the collapsible panel.

**Comment by azaslonov** [comment]
Btw, in a couple of weeks, we're bringing additional controls to configure responsive properties, that will make those pretty explicit.

**Comment by AnRei123** [comment]
ZarTrox did the alignment for both, the collapsible panel and the grid cell (aside). It seems to be a bug.

**Comment by azaslonov** [comment]
Can you please share the permalink or name of that test page (via email maybe)? I still can't repro this.

**Comment by azaslonov** [comment]
I actually found one of the pages, and confirmed my suspicion, - on smaller screen sizes, the alignment was "center". It is not super obvious, that's why I was talking about new UI for responsive properties that would explicitly tell you about how it's configured.

Meanwhile, please try to do this: While having "Article" (same goes to  "Aside", "Footer" etc.) editor open, switch between the screen sizes. You'll see that alignment (and other properties) of the "Article" change. This way, switching to a specific size, you can set desired values for each size.

![image](https://user-images.githubusercontent.com/2320302/115595889-4fa0ee00-a28c-11eb-8459-9df3ec8de77e.png)

**Comment by ZarTrox** [comment]
Thank you. The fact that the different screen sizes are not just for display is new to me.

**Comment by AnRei123** [comment]
Yes, thanks. This fixed the issue. But still, for very small resolutions NO HAMBURGER item appears. Thus, for smartphones, there is currently no possibility for the users to navigate through our portal pages. With the very small window resolutions, there is no menu anymore at all. Could you fix this issue?
