### ISSUE TITLE
API console doesn't receive token from OAuth (Client Credentials flow)

### ISSUE THREAD

**Issue by martinsamanek** [Azure/api-management-developer-portal#1274]
## Bug description

The token is not passed back to API console after client credentials successful login 

## Reproduction steps

1. Go to an endpoint in API with predefined OAuth 2.0 login
2. Open Try It console
3. Select Client Credentials in Authorization
4. PopUp which calls Identity server is quickly opened and the Identity Server returns token
5. PopUp is closed but the token is not populated in Console

### Local test:
![LocalTest](https://user-images.githubusercontent.com/43401497/116090655-64262180-a6a4-11eb-80d2-fcf36c8e85c0.gif)
### Storage test:
![StorageTest](https://user-images.githubusercontent.com/43401497/116091744-6f2d8180-a6a5-11eb-9a00-32f163f619b1.gif)

## Expected behaviour

The returned token is populated in the console

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

2.8.0

## API Management service name

apimoritest

## Environment
[https://apimoritestportal.z6.web.core.windows.net/](https://apimoritestportal.z6.web.core.windows.net/)
 - Operating system: Windows 10
 - Browser: Google Chrome
 - Version: 90.0.4430.85
- same behaviour in Edge and Firefox

## Additional context

Tested on new APIM instance with default API. Only OAuth settings added and published API.
Same behaviour also for Implicit flow

It's working correctly in managed version:
![ManagedVersion](https://user-images.githubusercontent.com/43401497/116089457-2e346d80-a6a3-11eb-97ad-072d39099276.gif)

**Comment by azaslonov** [comment]
Hi @martinsamanek, since you self-host the portal, there is no portal's backend to communicate the token using `client credentials` flow.

At some point, we'll probably add an option to re-use our backend endpoints for OAuth scenarios (specifically, we'll need to solve CORS configuration problem), but for now you have two options: use `implicit` grant flow (which doesn't require the backend), or implement your own endpoint for `client credentials` flow (i.e. using Azure Functions) with proper CORS settings.

**Comment by martinsamanek** [comment]
I'm sorry, but I don't understand this. **Implicit flow also doesn't work.** Implicit flow uses APIM backend also. Check this, the same issue:
![ImplicitTest](https://user-images.githubusercontent.com/43401497/116140848-335fdf80-a6d8-11eb-8d29-59c18bc47393.gif)

If I'm not mistaken, both flows worked last week. Wasn't there a change in APIM code (not developer portal). Because it is still working in a way, that the request is send to our identity server and token returned. Only the popup event with message is not caught by developer portal code. You can check the URL created by APIM backend: [https://apimoritest.developer.azure-api.net/signin-oauth/credentials/identity-server-dev](https://apimoritest.developer.azure-api.net/signin-oauth/credentials/identity-server-dev) which is opened by developer portal. If you check the source code, the token is in place and Javascript should send it in a message.

And the same issue with the Implicit. It is returned but not passed to developer portal. Honestly, this is crucial function for all our consumers and developers also. 

Do you want to say, that the whole code in oauthService.ts cannot be used on selfhosted portal?

**Comment by azaslonov** [comment]
Sorry, my bad. Right, `implicit` flow also requires the backend. So yes, the whole oauthService.ts won't work for self-hosted out of the box (at least right now), but you can fairly quickly implement your own OAuth flow handlers with i.e. Azure Functions and [client-oauth2](https://www.npmjs.com/package/client-oauth2) library.

**Comment by martinsamanek** [comment]
Ok, but honestly I don't like that you turned off existing feature without further notice. Even without code update. :(

**Comment by GuillaumeBONHOMMEAU** [comment]
We got the same issue.
The "Authorization code grant flow" is called successfully.
With {{apimName}}.developer.azure-api.net/signin-oauth/code/callback/{{authorizationServerName}}.
 A token is returned and is valid.
 
Problem is, as noticed @martinsamanek, the origin window initiating this request does not catch the response.
Using Fiddler, we can see callback response. Something like :

![image](https://user-images.githubusercontent.com/25102672/116700685-57b50800-a9c7-11eb-82da-027cd8729736.png)

The problem is the second parameter of "postMessage" function.
The "targetOrigin" is the URL of the managed APIM developer portal.
As we use a self-hosted dev portal, the domain does not match, so we do not catch the answer with the token.
If I catch thoses response with Fiddler and specify the correct origin, our dev portal do work without any problem.

I believe this is one of the recent fix. TargetOrigin must be specified for security reason. On that there is no problem.
Yet, self-hosted APIM dev portal should have a way to work.
Or may you could provide us a way to specify the correct origin :)

**Comment by akga** [comment]
I have the same issue and found a crude workaround. By doing a http get on  {{apimName}}.developer.azure-api.net/signin-oauth/code/callback/{{authorizationServerName}} we can extract access token.

Change method _authenticateClientCredentials_ in **src/services/oauthService.ts** as follow:
 
```
    public async authenticateClientCredentials(backendUrl: string, authorizationServer: AuthorizationServer): Promise<string> {
        let uri = `${backendUrl}/signin-oauth/credentials/${authorizationServer.name}`;

        if (authorizationServer.scopes) {
            const scopesString = authorizationServer.scopes.join(" ");
            uri += `?scopes=${encodeURIComponent(scopesString)}`;
        }

        try{
            const response = await this.httpClient.send<any>({
                method: HttpMethod.get,
                url: uri
            });

            const match1 = response.toText().match("accessToken:.*\"(.*)\"");
            const match2 = response.toText().match("accessTokenType:.*\"(.*)\"");

            if(match1 && match2){
                const accessToken = match1[1];
                const accessTokenType = match2[1];
                return(`${accessTokenType} ${accessToken}`);
            }else{
                console.log("Error in getting access token using Client credential flow");
            }

        }
        catch (error) {
                console.log("Client credential token error: " + error);
            }
    }
```
I managed to get the token in console with this change. It's not perfect but works till its fixed by Microsoft.

**Comment by ErikMogensen** [comment]
@azaslonov, what do you think of the workaround above?

**Comment by azaslonov** [comment]
This may work for client credentials flow because it doesn't require popup, but I think you guys should wait for proper solution with the right policies in place.
