### ISSUE TITLE
Responsiveness issue on API details page (resolve truncated texts and navigation items)

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1277]
## Bug description

On the API details page the "API: details"-widget overlaps with an adjacent "Aside"-element when the screen size is set to "medium screen".

![image](https://user-images.githubusercontent.com/58420097/116197179-b020a700-a734-11eb-8cd0-0ec2a22677cc.png)

Here the text and the box should not overlap with the text on the side.

This also occurs with other widgets like the "List of operations"-widget.
![image](https://user-images.githubusercontent.com/58420097/116197959-a9defa80-a735-11eb-8e85-c448d337c237.png)

## Reproduction steps

1. Create a Section with an "Aside" and an "Article" on the API details page.
2. Add e.g. the "API: details" widget to the left one.
3. Add some text to the other one.
4. Set screen size to "medium screen".
5. See error

## Expected behavior

Every element behaves responsively in a way so that they are correctly displayed in a new line and are not overlapping.

## Is your portal managed or self-hosted?

Managed

---

@AnRei123

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
