### ISSUE TITLE
Changing block type changes type of text 

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1282]
## Bug description

Changing the block type from e.g. Header 1 to Header 2 also impacts the first paragraph of the text element and sets the style to the new block type.

![2021-04-27_11-37-07](https://user-images.githubusercontent.com/58420097/116220550-1285a180-a74d-11eb-944a-dfee17a24cb4.gif)

A workaround we found is to clear cookies and the local storage in the Developer Console.
![image](https://user-images.githubusercontent.com/58420097/116222187-a1df8480-a74e-11eb-9c7d-4f2487b9cbd9.png)

Developer Console - Application - Local Storage - Right-click on Portal link -  Clear
Developer Console - Application - Cookies - Right-click on Portal link - Clear
After doing this it works normally for a while again.

Before doing the clear there have been a few more of these error messages. Not sure if this has anything to do with this topic.
![image](https://user-images.githubusercontent.com/58420097/116221904-5927cb80-a74e-11eb-9bd8-1c3d32ed7691.png)

## Reproduction steps

1. Create at least one text element.
2. Select only the header of one text element.
3. Change the header to any other block type.
4. See that not only the header changes but also the first paragraph.

## Expected behavior

Only the selected string gets the new block type assigned.

## Is your portal managed or self-hosted?

Managed

---
@AnRei123

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
