### ISSUE TITLE
Using dynamic links to the most current version of an API operation

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1303]
## Bug description

For some API descriptions, it is required to reference to operations of the same or other APIs. 
Currently, to link to an API operation, you must always provide a dedicated API version in the URL or relative path.
If there is a newer version for an operation available, the author of an article in the DevPortal or of the API specifications shown on the API details pages might not be aware of a change or might not like to invest the efforts to update the links in the code

Therefore, in a lot of cases, you would like to link to the latest version of an API operation to ensure that the link does not get outdated when deprecating or removing the referenced version of an operation. Or at least to minimize the risk.

## Expected behavior

There should be a possibility to use a placeholder in links to operation details for the version info such as "latest".
If the URL consists of the placeholder string, the portal back-end should check the latest API version for the referenced operation and redirect the user to the operation details page of the latest API version.

## Is your portal managed or self-hosted?

Managed

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
