### ISSUE TITLE
Picture Transformation: Translate X / Y, is no longer working for negative values.

### ISSUE THREAD

**Issue by Ledger94** [Azure/api-management-developer-portal#1322]
## Bug description

Picture Transformation: Translate X / Y, is no longer working for negative values.

## Reproduction steps

1. Open portal page (designer)
2. Click on styles
3. Add a picture variation
4. Modify Transformation: Translate X / Y, for the picture with a negative value
5. Notice that the picture is still in it's default position

## Expected behavior

Picture transformation for negative values should work. It previously worked in version 2.7.1

## Is your portal managed or self-hosted?

Managed

## API Management service name

IAPEMEA

## Environment

 - Operating system: Windows 10
 - Browser: Google Chrome
 - Version: 90.0.4430.212

**Comment by azaslonov** [comment]
Hi @Ledger94, let me check and fix, if that's the case.

**Comment by Ledger94** [comment]
Thank you for looking into this, if you have any questions, let me know.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
