### ISSUE TITLE
API definition export

### ISSUE THREAD

**Issue by AdeZwart** [Azure/api-management-developer-portal#1361]
## Bug description

On our developer portal we have the "API details" component on the "API details" page which shows a dropdown that can generate an API definition. This dropdown is used by our integrators to generate code with NSwagStudio. 

Currently when the YAML or JSON definitions are selected the request only returns:
`Unable to convert message to API definition`

Not any indication on why it's unable to convert the message to the API definition.

This behavior started on 7 out of 9 of our API's around June 8th.

## Expected behavior

The API details component is able to export a valid API definition or gives a clear error description in case it's unable to.

## Is your portal managed or self-hosted?

Managed 

![2021-06-30_11h02_17](https://user-images.githubusercontent.com/8612100/123933646-dbbd4900-d992-11eb-8da5-2e79f1ad278a.png)

**Comment by mikebudzynski** [comment]
@AdeZwart, a fix for this issue will be rolled out with the next API Management service release. It may take several weeks for your service to receive the update (starting from July 6).

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
