### ISSUE TITLE
Cannot open DevPortal in editing/designer mode after triggering publishing anymore

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1367]
## Bug description / expected behavior

Since this week, I cannot open DevPortal in editing/designer mode after triggering publishing for about 2 minutes. Even if the DevPortal in editing/designer mode is already open, after triggering publishing there are several loading issues.

As I need often to publish to test how the modified content is reflecting in the published mode, these times of unavailability are too long. I need to be able to continuously work in the  editing/designer mode of the DevPortal. Please find a solution that publishing does not impact the availability of the DevPortal in editing/designer mode!!!!

## Is your portal managed or self-hosted?

Managed

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
