### ISSUE TITLE
Media container - adding a "link file" - UX issue

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1368]
## Bug description

Adding a "link file" to the media container is currently only possible through opening the media dialog from the main tool panel on the left in the editor/designer mode of the DevPortal. But I need to also be able to add or update a "link file" when modifying the image settings of a "picture" widget.
![Snag_317214](https://user-images.githubusercontent.com/58981351/125038683-fcbe2200-e095-11eb-9bb2-fed79e4c8c3c.png)

## Expected behavior

The option to add a "link file" should be also available from the settings dialog when modifying the settings for a picture widget.
![Snag_35dbc7](https://user-images.githubusercontent.com/58981351/125039331-a8677200-e096-11eb-81da-c06261829f89.png)

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
Good point, we'll add this.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
