### ISSUE TITLE
Issues with copying and pasting formatted text from one text widget to another one.

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#1372]
## Bug description

When copying and pasting formatted text from one text widget to another one, some inline formats get lost such as a specially assigned text color. This is very error prone, annoying and laborious.

## Reproduction steps

1. Select text snippet in a paragraph of a text widget and assign a customized text color.
2. Copy the whole paragraph with the assigned color format and paste it in another text widget.
3. Check the assigned color for the previously selected text snippet.
The previous color assignment is lost. The default font color is assigned instead.
4. Select the text snippet in the target again and assign again a customized text color.

## Expected behavior

Assigned inline format are correctly and completely kept during copying and pasting text across different web widgets.

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
Makes total sense. Thanks!

**Comment by Nzamuyejoram** [comment]
@azaslonov thanks for requesting on this feature. we gonna give a trial on it

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
