### ISSUE TITLE
File upload not working for multipart/form-data

### ISSUE THREAD

**Issue by Yogesh-BK** [Azure/api-management-developer-portal#1487]
## Bug description

When we publish an api using openApi specification and add an endpoint with request body "content-type = multipart/form-data", we are not able to see the Upload file option in developer portal

![image](https://user-images.githubusercontent.com/92719848/137707510-e93b3df7-50b4-492e-a810-7ccd985bad25.png)

## Reproduction steps

1. Add an api using openApi specification
2. Add an endpoint with the request body "content-type = multipart/form-data"
3. Open the developer portal, go to the endpoint and click on the **Try it** button
4. Upload file option is not displayed

## Expected behavior

Upload file option should be displayed

## Is your portal managed or self-hosted?

Managed 

## Environment

 - Operating system: MacOs Big Sur
 - Browser: Google Chrome

## Additional context

Following observations:
1. Json for openApi specification for swagger and APIM are different
2. Differences that we observed
     1. schema type is not added in requestBody -> content -> multipart/form-data in APIM openApi specification
     2. format for schema ->  properties ->  fileName is not added in requestBody -> content -> multipart/form-data in APIM openApi specification
     3. encoding ->  fileName ->  style is not added in requestBody -> content -> multipart/form-data in APIM openApi specification

Swagger openApi Specification:

![image](https://user-images.githubusercontent.com/92719848/137710236-979b14c5-9fca-43f5-b515-54dbb1806f00.png)

APIM openApi Specification:

![image](https://user-images.githubusercontent.com/92719848/137710400-710941bb-30c0-4510-8940-3b885fa145ff.png)

**Comment by ygrik** [comment]
Hi @Yogesh-BK 
Now we support OpenAPI 2.0 https://swagger.io/docs/specification/2-0/file-upload
To be able to see the Upload file option in the developer portal you should use **type: file**

**Comment by char000** [comment]
What would be expected timeline for getting this issue fixed?

**Comment by StefanPuntNL** [comment]
Pinging @mikebudzynski ;) Is there an eta for getting this issue fixed?

**Comment by cboschert-allegion** [comment]
Is there an update on this? We're more than a year past the ETA of first quarter 2022, so it'd be nice to get more information.

**Comment by NickBerto84** [comment]
Any news please?

**Comment by angusbreno** [comment]
@ygrik we are stuck here because we are using the generated openapi spec from APIM to be consumed and this 2 feature are blocking:
1 - Developer portal Multipart upload should be compatible with OpenApi Spec 9 (no changes in the spec need to be done)
2 - The developer poral should show upload file widget.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
