### ISSUE TITLE
Settings for the YouTube video player not transferred to all screen resolutions

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1490]
## Bug description

Size specifications for the YouTube video player are not transfered to different screen resolutions.
In comparison to the image widget where the size settings are transferred across all screen resolutions 

Extra large Resolution with Image:
![image](https://user-images.githubusercontent.com/58420097/138248827-3fd9586e-c245-46f7-b05a-4e81c9712b93.png)

Large Resolution with Image:
![image](https://user-images.githubusercontent.com/58420097/138249344-6a4ab0ad-537f-4a4f-a5b6-f724473b20ff.png)

 The YouTube Video player does not have this feature. You would need to set these settings for each resolution individually.

Extra large resolution with YouTube player:
![image](https://user-images.githubusercontent.com/58420097/138250145-bf2f9b10-afb1-4d22-a840-9b813ec075c1.png)

Large Resolution with YouTube player:
![image](https://user-images.githubusercontent.com/58420097/138250707-4f248cd3-fae9-4616-84bb-a9c6c65c8571.png)

To avoid mistakes and misunderstanding the video player should behave just as the images and have the same settings as the larger resolution unless you change it.

## Reproduction steps

1. Create youtube video player widget with size specifications
2. Switch to any other resolution
3. See error

## Is your portal managed or self-hosted?

Managed

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
