### ISSUE TITLE
Custom CSS for styling

### ISSUE THREAD

**Issue by cristianhosu** [Azure/api-management-developer-portal#151]
To be able to customize the look and feel you need to clone/download the repo, change stuff in it and then self-host it.
There should be a way in which a user can upload a custom CSS that would be injected globally.

**Comment by mikebudzynski** [comment]
Thanks, @cristianhosu for opening this request. Could you tell us more about why you need to inject CSS rather than style the portal through the provided functionality?

**Comment by cristianhosu** [comment]
@mikebudzynski I want to be able to style the buttons according to a clients corporate identity.
I want to be able to add animations when scrolling.
I want to be able to customize the layout in a different manner than already available through paper bits.
All of these can be done by allowing the add of custom css.

**Comment by mikebudzynski** [comment]
Thanks, @cristianhosu 

We do not support custom CSS or JS injection in the managed version of the portal, so that we can guarantee safety during service upgrades. If we allow for injection of custom CSS, we won't be able to check for compatibility of new portal releases with customers' portals, which may result in service upgrades breaking customers' portals.

We'd like to offer enough flexibility through the visual editor, so that CSS injection is not required. If you have particular asks in that area, please provide details.

**Comment by mohammadchehab** [comment]
In the case of changing the AAD or B2C buttons how can we change the styling of those?
