### ISSUE TITLE
Not recognizable template through permalink of a page. 

### ISSUE THREAD

**Issue by elisabethvolkinshtein** [Azure/api-management-developer-portal#1524]
## Bug description

While opening a page, you can see the permalink of the page. However the permalink dose not reveal which template the currently opened page is assigned to.
When you work with several layouts it is difficult to identify the right template.

For example:
- Template1
/docs/*

- Template2
/docs/services/*

- Template3
/docs/services/notifications/*

Page permalink: /docs/services/notifications/email 
You can not tell immediately which template it belongs to without going over all templates first.

## Reproduction steps

1. Create two different templates for example:
 - Template1
/docs/*

- Template2
/docs/services/*

2. Create two pages with each of the templates.
3. Try to figure out which page belongs to which template

![image](https://user-images.githubusercontent.com/90905584/140495075-0bd61a00-9dc0-45b9-82b4-d1fc78f16565.png )

## Expected behavior

- By opening the page configuration, you must be able to tell which template is being used in the specific page and you can directly switch  from a page to it's template.
-  The first part of the permalink, which indicates the template must be highlighted.
- Alternative: new field with the name of the used template.

 Example:

- Permalink Layout:
/docs/services/*

- Permalink Page:
**/docs/services**/Notifications/email

## Is your portal managed or self-hosted?

Managed

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
