### ISSUE TITLE
Using deep link to API page always takes you to the sign in page

### ISSUE THREAD

**Issue by dhall19** [Azure/api-management-developer-portal#1554]
## Bug description

We host a site that contains deep links to APIs which look like this:

`<a href="https://ourportalpage.com/api-details#api=anApp" target="_blank" >test</a>`

However while this URL works when we paste it into a browser tab, when a user clicks on the link on our site they are redirected to the sign-in page even if they are already signed in, and when they do sign in they are not redirected to the API page.

Is there anything else we should be doing to get these links to work?

## Reproduction steps

1. Create an html file with an link as described above
2. Open file in browser
3. Click link
4. You are taken to sign in page whether or not you have signed in.

## Expected behavior

When the user isn't signed in, the link takes them to the sign in page, then on to the API page once they are signed in.
When the used has already signed in, they are taken straight to the API page.

## Is your portal managed or self-hosted?

Managed

**Comment by s8mathur** [comment]
+1 for the importance of this bug to how we use the portal deep links too.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
