### ISSUE TITLE
GraphQL Test Console, doesnt include the version in the path

### ISSUE THREAD

**Issue by UniperMaster** [Azure/api-management-developer-portal#1609]
## Bug description

The uri endpoint on the test console doesn't get included in the path, so when you click **try it** you get a 404 not found. It works OK for the  Azure APIM service test tab and via postman 

![image](https://user-images.githubusercontent.com/58111142/150798347-e53b8cb3-5d8a-446d-80ed-55fa3e7b6555.png)

![image](https://user-images.githubusercontent.com/58111142/150799157-6a32fb98-9f68-472c-8456-21ba8053ae07.png)

## Reproduction steps

1. Go to 'Developer Portal.'
2. Select a GraphQL endpiont with a versioning set enabled (path)
2. Click on '**try it**'
3. Enter Query
4. See error 404

![image](https://user-images.githubusercontent.com/58111142/150799582-b0510f09-9e11-43d7-9d49-5cac354cd05d.png)

## Expected behavior

Query to executed with a **200** response

## Is your portal managed or self-hosted?

Managed 

## Release tag or commit SHA (if using self-hosted version)

n/a

## API Management service name

uniperapi-dev

## Environment

 - Operating system: [windows]
 - Browser: [Edge Dev build]
 - Version: [Version 99.0.1135.5 (Official build) dev (64-bit)]

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
