### ISSUE TITLE
Impossible to generate requests with "%2F"

### ISSUE THREAD

**Issue by esoterra** [Azure/api-management-developer-portal#1625]
## Bug description
It is not possible to generate requests containing `%2F`, the singly encoded `/` from the tester UI.

## Reproduction steps

1. Click an API Operation
2. Click the "Test" heading
3. Provide an input field (template parameter or query parameter)
   a. A value containing `/`
   b. A value containing `%2F`

The result of test 3.a is that the slash passes through and shows up in the trace as `/`.
The result of test 3.b is that the `%2F` is re-encoded and shows up in the trace as `%252F`
This makes it impossible to generate requests with parameters that singly-encode `/` as `%2F`.

## Expected behavior

Either
A. the `/` character should be encoded as `%2F`,
B. the `%` character should not be re-encoded, or
C. the encoding behavior of these fields should be user-controllable.

## Is your portal managed or self-hosted?

Managed

## API Management service name

Message kybrown for service details if needed.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
