### ISSUE TITLE
Maps is not working in APIM Developer portal in edit mode

### ISSUE THREAD

**Issue by pselvanayagam** [Azure/api-management-developer-portal#1647]
## Bug description

When we try to add Map in the edit mode of Developer portal, it shows error "Oops, something went wrong" and map doesn't load.

## Reproduction steps

1. Go to APIM Developer portal in edit mode
2. Try to add Map widget.

## Expected behavior

When we try to add Map in the edit mode of Developer portal , map should load.

## Is your portal managed or self-hosted?

Managed

**Comment by s8mathur** [comment]
Was going to open the same bug. Map is empty. A minimum competent map widget should have the following functionality, IMO: 
1. Loads out of the box. 
2. Has a default map marker preconfigured as a appropriate aspect ration and bounding box SVG image. (currently you have pick an image explicitly from image gallery which is a terrible idea for default functionality) 
3. Allows picking of atleast 3 map providers : Bing Maps, Google Maps, MapBox Maps with ability to specify keys and style files for each
4. Key use case such as asking the Map to re-render when data in main frame changes via (say) `postMessage()` is key to basic usability - otherwise please specify how to pass data and events to/from the map widget to the rest of the document.

**Comment by azaslonov** [comment]
Fix for managed version is being rolled out.
