### ISSUE TITLE
After Logging in using ADB2C, not redirecting to the custom reply url mentioned in the AD B2C button.

### ISSUE THREAD

**Issue by pselvanayagam** [Azure/api-management-developer-portal#1661]
## Bug description

When we Sign in using ADB2C from the Developer portal, we are not getting redirecting to custom reply url mentioned in the AD B2C button. Its always redirecting to the Home page in case of AD B2C.

## Reproduction steps

1. Go to APIM Developer Portal edit mode
2. Click on edit in AD B2C button and add a custom reply url .
3. Login through AD B2C 
4. See the redirected page and also the redirect_uri in the AD B2C url. 

## Expected behavior

When we Sign in using AD B2C from the Developer portal, it should be redirected to the  custom reply url mentioned in the AD B2C button. Its should not  always redirect to the Home page in case of AD B2C. We are seeing proper redirect_uri in the AD B2C pop up. But its not redirecting to the redirect_uri mentioned.
Also enhance the capability of AD B2C window behavior. It will be good if AD B2C opens in a new window instead of a pop up.

## Is your portal managed or self-hosted?

Managed

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
