### ISSUE TITLE
Try out Panel : Template parameter name length> 20 chars is not getting displayed completely on UI 

### ISSUE THREAD

**Issue by patidar-jaishree** [Azure/api-management-developer-portal#1674]
## Bug description

Try out Panel : Template parameter name length> 20 chars is not getting displayed completely on UI.

MacOS + Chrome
![image](https://user-images.githubusercontent.com/41952531/155985002-c7efe107-e5da-463b-96c2-df820d2a2aab.png)

## Reproduction steps

1. Publish an endpoint with template parameter name length>20 (Eg. LongNameTemplateParameterName)
2. Go to the endpoint details on developer portal and click on "Try it"
3. Try out Panel is displayed.

## Expected behavior

User should be able to read complete name of template parameter. I can also be handled by adding ellipses which shows complete text on hover.

## Is your portal managed or self-hosted?

Managed

## Environment
Latest version of following browsers
 - MacOS - Chrome, Safari & Firefox 
 - Windows 11 - Edge

## Additional context

MacOS + Safari
<img width="586" alt="image" src="https://user-images.githubusercontent.com/41952531/155986615-e70c5811-4fc6-45e9-8262-d50911fd0b5f.png">

MacOS + Firefox
<img width="590" alt="image" src="https://user-images.githubusercontent.com/41952531/155986677-8b38fd81-0bc1-4552-933f-0627eb197d9f.png">

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
