### ISSUE TITLE
Swagger property not displayed even if present in the .json definition file

### ISSUE THREAD

**Issue by cosminstirbu** [Azure/api-management-developer-portal#1691]
## Bug description

As per the attached screenshots, property `code` from `RequestProcessingError` is present in the definition file but not displayed in the portal.

## Expected behavior

Property should be displayed in the portal.

## Is your portal managed or self-hosted?

Managed

## Additional context

![Screenshot 2022-03-15 at 14 33 36](https://user-images.githubusercontent.com/7135690/158380127-a73310e3-eb2c-4f37-9a3a-4220cd69df27.png)
![Screenshot 2022-03-15 at 14 33 26](https://user-images.githubusercontent.com/7135690/158380135-62de70b4-cb63-4373-a075-09655315e1f1.png)

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
