### ISSUE TITLE
Change/Resert Password 

### ISSUE THREAD

**Issue by senthilkumardhanapal2** [Azure/api-management-developer-portal#1727]
## Bug description

Developer able to keep the same password as before while change or reset the password

## Reproduction steps

1. Go to 'https://prepmmmtzinterop.developer.healthtranzformdev.com/signin'
2. once you login into developer portal
3. Click on 'Profile'
4. Scroll down to 'Change Password'
5. enter current password, new password, confirm password

## Expected behavior

user should be thrown error stating cant use some of the previous password as new password

## Is your portal managed or self-hosted?

Managed 
https://prepmmmtzinterop.developer.healthtranzformdev.com/

## API Management service name

[ptzio03wummmapim]

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by mikebudzynski** [comment]
@senthilkumardhanapal2, why is this a problem?

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
