### ISSUE TITLE
HTTP 404 status on GET openidConnectProviders on latest self-hosted (2.17.0)

### ISSUE THREAD

**Issue by erwinkramer** [Azure/api-management-developer-portal#1828]
## Bug description

Not able to GET openidConnectProviders on latest self-hosted (2.17.0)

## Reproduction steps
I've replaced my portal url with: **myapimportal.com** and the provider as **myprovider** as a sample. They do match with the developer portal that i'm pointing towards. 

1. Go to an API on the developer portal with an openidConnect Provider configured. 
2. Check the browser console
4. See error (this message is based on the latest commit, not on 2.17.0 as I've seen that one displays a CORS message wrongly): 
```

GET https://myapimportal.com/openidConnectProviders/myprovider 404

Unable to fetch configured authorization servers. Error: Unable to handle response from URL https://myapimportal.com/openidConnectProviders/myprovider .

Uncaught (in promise) Error: Unable to fetch configured authorization servers. Error: Unable to handle response from URL https://myapimportal.com/openidConnectProviders/myprovider .
```

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

[2.17.0](https://github.com/Azure/api-management-developer-portal/releases/tag/2.17.0) and b9f96a5b41d924dcd56df794859dd38748714003 (latest)

Did not happen on [2.16.0](https://github.com/Azure/api-management-developer-portal/releases/tag/2.16.0)

## API Management service name

Can provide if needed.

**Comment by azaslonov** [comment]
@erwinkramer, right, this is because `/openidConnectProviders/{provider}` is a backend operation which requires access to the secrets, etc. It of course doesn't present on self-hosted portal (if you host it on the blob storage for instance). However, you could still use the APIM backend if you specify `backendUrl` setting pointing to it in the `config.json` file of your published portal. In addition to that, you'd need to configure CORS settings for the portal backend, which you can do in this blade:

![image](https://user-images.githubusercontent.com/2320302/177447030-7f85a9a3-1fb4-4a16-b08d-62c0ba130697.png)

@mikebudzynski, I think this scenario deserved documentation.

**Comment by erwinkramer** [comment]
@azaslonov, @mikebudzynski, please note that it was working in the previous version for me, I've already specified backendUrl in the config.json and I've specified the cors settings too. And actually backendUrl points to the portal url (instance.developer.azure-api.net) As documented on the Ms docs. So I'm not sure how this is going to work, I've checked the implementation inside the portal code, but it just seems to be a missing implementation (just like the error message states). Could you please test it yourself?
