### ISSUE TITLE
Delegating Product Subscription only causes sign-in/sign-up requests to be sent to the delegation endpoint.

### ISSUE THREAD

**Issue by webdes03** [Azure/api-management-developer-portal#1833]
## Bug description

When configuring delegation on a new APIM instance, electing to delegate product subscription, but not sign-in & sign-up, results in the portal's sign in and sign up buttons redirecting to the delegation endpoint instead of using APIMs native user management.

## Reproduction steps

1. Create a new APIM instance
2. Navigate to the `Delegation` blade, check the `Delegate product subscription` box, but do not check the `Delegate sign-in & sign-up` box. Enter a valid delegation endpoint URL and generate a validation key. Save the page.
3. Navigate to the `Portal overview` blade's Overview tab, click Publish. Monitor the Revisions tab for completed publishing
4. Open incognito browser and navigate to your developer portal URL
5. Click "Sign Up"

## Expected behavior

When delegation of sign-in/sign-up is not selected, the APIM portal's native user management should be used.

## Is your portal managed or self-hosted?

Managed

## Additional context

![image](https://user-images.githubusercontent.com/371941/174920804-b8f33f30-1574-4783-a9f8-af2a8f317836.png)

![image](https://user-images.githubusercontent.com/371941/174920907-3fa1ea22-b294-42a9-a115-cec25a31a762.png)

![image](https://user-images.githubusercontent.com/371941/174920952-08cb5fd6-a7ea-4e2f-9bc2-4e1fe7cd3794.png)

**Comment by webdes03** [comment]
Bump. Is there any updates on this obvious bug?

**Comment by ygrik** [comment]
Hi @webdes03 
This is known issue. The fix will be deployed with the next release (ETA 1-2 months)

**Comment by webdes03** [comment]
ETA was 1-2 months back in June... it's now September. Is there any update on this or should I look at alternatives to APIM? @ygrik @azaslonov

**Comment by ygrik** [comment]
Hi @webdes03 
Could you please provide your portal and service versions?
You can do it with Get request **https://{service name}.developer.azure-api.net/internal-status-0123456789abcdef**
The response should be like this one:
**{"Status":200,"PortalVersion":"20220727101650","CodeVersion":"20220822193921","Version":"0.30.1742.0"}**

**Comment by webdes03** [comment]
`{"Status":200,"PortalVersion":"20220621204347","CodeVersion":"20220822193921","Version":"0.30.1765.0","RoleNumber":"gwhost_2"}`

**Comment by ygrik** [comment]
@webdes03 
Just tested on my APIM service and can't reproduce your issue
My service has the same version 

> {
>      "Status":200,
>      "PortalVersion":"20220906134812",
>      "CodeVersion":"20220822193921",
>      "Version":"0.30.1765.0",
>      "RoleNumber":"gwhost_1"
> }

Could you please provide your service name to apimportalfeedback@microsoft.com or create a support ticket for further investigation?

PS
From your "PortalVersion":"20220621204347" it looks like you didn't republish your portal since June 6

**Comment by webdes03** [comment]
Let me do some checking on my end, I haven't republished or attempted to try using all of this again since the issue was still marked as an open P0. I expected it to get closed and tagged to a release if/when it was resolved.

Let me test and I'll follow up if I still see it.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
