### ISSUE TITLE
Behavior differences of menu item links in published version

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#1857]
## Bug description

A link to a page in a menu item is working properly in the editor mode of the DevPortal.
The published DevPortal of this instance on the other hand has the issue that this link does not work.

Clicking on the menu item link does not forward one to the designated page.

Editor mode (with pressing ctrl):
![2022-07-12_12-11-23](https://user-images.githubusercontent.com/58420097/178467703-6789f354-936f-4c2f-868f-c892d3c7149d.gif)

Published portal:
![2022-07-12_12-12-39](https://user-images.githubusercontent.com/58420097/178467933-fe906ee2-59d3-4ccd-913d-0390397d0695.gif)

The correct settings for this menu item have been set:
![image](https://user-images.githubusercontent.com/58420097/178468486-f787a3c8-305c-461f-bcec-e2a7ceb10e3d.png)
Only one "What's new" exists.

The published DevPortal has been opened in the Incognito mode and the editor mode has been opened in "normal" chrome.

## Reproduction steps

Cannot be reproduced by me.

## Is your portal managed or self-hosted?

Managed

## API Management service name

apiteamplayuxsource

Other environments are affected as well.

## Environment

 - Browser: Chrome
 - Version: Version 103.0.5060.114

@AnRei123

**Comment by azaslonov** [comment]
Thanks @ZarTrox, I see where the problem is, we'll fix this.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
