### ISSUE TITLE
File responses not interpreted correctly

### ISSUE THREAD

**Issue by LaunchPairs** [Azure/api-management-developer-portal#1984]
## Bug description

Responses from file download resources are not interpreted correctly by the portal

## Reproduction steps

If an API (resource) delivers a file as response and specifies this in the response header according to the content disposition (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition), the response is displayed as hieroglyphics. 

Example response header: 
`Content-Disposition: attachment; filename*=UTF-8''myfile.pdf`

## Expected behavior

Either the download dialog of the web browser should appear directly or a link should be displayed with which the download can be triggered. The product Swagger.UI solves this for example with the second variant.

## Is your portal managed or self-hosted?

Managed

**Comment by jsorohova** [comment]
Hello @LaunchPairs, thank you for reporting the issue. Yes, Content-Disposition header currently is not supported but the downloads should work fine if you specify the downloadable file path through Frontend tab as per image below. 
![image](https://user-images.githubusercontent.com/92329687/199737189-c11bef68-9095-4613-8bd8-4a9dc86d4845.png)

If you need more info, you can comment here or send your definitions specification file to us to [apimportalfeedback@microsoft.com](mailto:apimportalfeedback@microsoft.com).

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
