### ISSUE TITLE
Register button jumps around when hover of the Login button

### ISSUE THREAD

**Issue by dzemp** [Azure/api-management-developer-portal#2002]
## Bug description
When you hover over the Login button with your mouse, the Register buttons jumps around on the screen (changes position). Tried it with Chrome version 107.0.5304.107 (Official Build) (64-bit) and  Edge version 109.0.1481.0 (Official build) dev (64-bit) on Windows 11. 

## Reproduction steps

1. Go to published Developer portal. 
2. Hover over the Login button.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 11
 - Browser: Chrome version 107.0.5304.107 (Official Build) (64-bit) and  Edge version 109.0.1481.0 (Official build) dev (64-bit)

**Comment by JMach1** [comment]
Hi @dzemp,

I was unable to reproduce the issue. Could you send me a link to your published Dev Portal, where you see it?

If you don't feel comfortable putting it publicly, you can send it to [apimportalfeedback@microsoft.com](mailto:apimportalfeedback@microsoft.com).

Thank you for reaching out!

**Comment by dzemp** [comment]
Thanks @JMach1 , sent an email with further information.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
