### ISSUE TITLE
Delegation lacks filled `returnUrl` query parameter

### ISSUE THREAD

**Issue by aristosvo** [Azure/api-management-developer-portal#2017]
**Every bug report should have precise description and reproduction steps; console traces or source code references are appreciated.**

**For assistance requests, contact Azure support or submit a post [on Stack Overflow](http://aka.ms/apimso). We don't provide support through GitHub Issues. Feature requests can be raised [on the Azure Feedback Forum](https://aka.ms/apimwish).**

## Bug description

The `returnUrl` on login with delegation is set to `/` instead of the developer portal URL

## Expected behavior

`returnUrl=<developer portal url>`

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

[20221122181334](https://portal.azure.com/?bundlingKind=DefaultPartitioner&configHash=_8irjNS3ewrg&env=portal&helppanenewdesign=true&l=en.en-us&pageVersion=10.204.0.116564.221111-2008#)

## API Management service name

[apim-itp-sandbox]

## Environment

 - Operating system: [macOS]
 - Browser: [Safari]

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by malincrist** [comment]
Hello @aristosvo , the returnURL is a relative URL that we use to navigate the user to the same relative path after a successful login.

From the delegation endpoint you should not navigate to the returnURL that we have in developer portal, but rather to a URL that respects this pattern:
https://\<service-name\>.developer.azure-api.net/signin-sso?token=<URL-encoded token>&returnUrl=%2Freturn%2Furl

Please check the steps to configure your delegation endpoint from [here](https://learn.microsoft.com/en-us/azure/api-management/api-management-howto-setup-delegation#create-your-delegation-endpoint).

This is the expected behavior: the returnURL is set to '\\' by default, when the login started from the home page.
