### ISSUE TITLE
User access not removed from dev portal after Azure AD Group membership is updated

### ISSUE THREAD

**Issue by san360** [Azure/api-management-developer-portal#2035]
## Bug description

User access not removed from dev portal after Azure AD Group membership is updated

## Reproduction steps

1. Configure dev portal with Azure AD group integration
2. Configure product access control to Azure AD group
3. Login with user who is member of Azure AD group
4. Updated Azure AD group membership to remove the above signed-in user
5. Login with same user to dev portal and user can still access the product

## Expected behavior

Removed user from Azure AD should not be able to see the product after user has been removed from AD group

## Is your portal managed or self-hosted?

Managed 

## API Management service name

san360-apim-int

## Environment

 - Operating system: [e.g., iOS]
 - Browser: [e.g., Google Chrome, Safari]
 - Version: [e.g., 22]

**Comment by malincrist** [comment]
Hello @san360 ,
After the user is removed from the AAD Group, it takes some time for the change to be propagated. Also, if the user does not sign out and sign back in, it may take even longer until the token expires and a new one is generated with proper permissions.

Could you please check if you still encounter this issue?

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
