### ISSUE TITLE
Scheduling the publish step via scripts yields a failed revision

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#2045]
## Bug description

When scheduling/starting the publishing of a DevPortal instance via the scripts (v2 or v3) the revision displays the status "failed" after a few minutes of the "Pending" state.

![image](https://user-images.githubusercontent.com/58420097/209304950-5c868a63-cc0c-43c8-8c9f-c80321073bf8.png)

The issue also appears sometimes when publishing in the revisions tab.

Observation:
When publishing with the scripts, the result in the console is "Done" as the request is not faulty and actually triggers the publishing step.

As this is a reoccurring issue for us are there any measures that can be taken to find out the issues with the APIM service?

## Is your portal managed or self-hosted?

Managed

## References

#1357 
#1377

**Comment by ZarTrox** [comment]
Sorry for the late response.

After testing and using the mentioned approach it still did not work for my test environment.
But when backing up the environment I noticed that the data.json had some issues.
After uploading an older but working data.json the publishing worked again.

Are there known issues with the data.json? And if yes are there plans to prevent this?

I can send the data.json to the mail if you want.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
