### ISSUE TITLE
APIM does not hide the delegation key in the Azure portal

### ISSUE THREAD

**Issue by ika-microsoft** [Azure/api-management-developer-portal#2053]
**Every bug report should have precise description and reproduction steps; console traces or source code references are appreciated.**

**For assistance requests, contact Azure support or submit a post [on Stack Overflow](http://aka.ms/apimso). We don't provide support through GitHub Issues. Feature requests can be raised [on the Azure Feedback Forum](https://aka.ms/apimwish).**

## Bug description
When going to Azure portal, the delegation key is shown directly not hidden. 

Also (not part of this bug) there is no notion of rotation (primary secondary)

A clear and concise description of the bug.

## Reproduction steps

1. Go to Azure portal
2. Click on APIM
3. Scroll down to Delegation
4. See the exposed key

## Is your portal managed or self-hosted?

Managed / Self-hosted

## Release tag or commit SHA (if using self-hosted version)

[e.g., release `2.0.0`, commit `c45da9778b70d369aba60fa2e63c191efe2b548f`]

## API Management service name

[e.g., contoso-api]

## Environment

 - Operating system: [e.g., iOS]
 - Browser: [e.g., Google Chrome, Safari]
 - Version: [e.g., 22]

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by atuannguyen1101** [comment]
Acknowledged, work item created https://msazure.visualstudio.com/One/_workitems/edit/16779412

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
