### ISSUE TITLE
Cannot deploy new change of developer portal

### ISSUE THREAD

**Issue by titan-khang** [Azure/api-management-developer-portal#2054]
**Every bug report should have precise description and reproduction steps; console traces or source code references are appreciated.**

**For assistance requests, contact Azure support or submit a post [on Stack Overflow](http://aka.ms/apimso). We don't provide support through GitHub Issues. Feature requests can be raised [on the Azure Feedback Forum](https://aka.ms/apimwish).**

## Bug description

Recently I cannot deploy new change of my developer portal page. I can save it in the customization page but after selecting Public website, it ends up with status Failed and the changed do not applied to production. 
I'm not sure if it is because of some of my changes or not. I did some changes on text label, navigation menus, added some images,... It displays fine on the customization page but failed to deploy. I don't know if there are some kinds of log that I can check to pinpoint the exact problem.

## Reproduction steps

1. Go to Developer Portal Customization Page
2. Click on Public Website 
![image](https://user-images.githubusercontent.com/111964394/209923982-600c4a3e-7273-435a-987e-ce9b446f8fcb.png)
3. Go to Azure Portal -> Portal overview -> Revisions
4. The newly created revision will have Failed status
![image](https://user-images.githubusercontent.com/111964394/209924361-8f06988f-19c2-4ce6-b420-d587f74639b7.png)

## Expected behavior

The new revision should have status Completed and marked as current.

## Is your portal managed or self-hosted?

Managed

## API Management service name

myTitanApi

## Environment

 - Operating system: Windows 10
 - Browser: Google Chrome
 - Version: 103.0.5060.114

**Comment by Swegsley** [comment]
Having the exact same issue since Friday 30th. Opened a support ticket via the azure portal already.

**Comment by ZarTrox** [comment]
Similar issue from me: #2045

**Comment by Swegsley** [comment]
I have a response from MS support:
This might be due to pop-ups being enabled on the developer portal which is available there already but not yet fully supported (breaking the portal bascially).

Solution is to run a content delete call through here:
https://learn.microsoft.com/en-us/rest/api/apimanagement/current-ga/content-item/delete?tabs=HTTP#code-try-0

Parameters:

- contentItemId* = main-menu-popup
- contentTypeId = popup
- resourceGroupName = YourResourceGroupNameHere
- serviceName = YourServiceNameHere
- subscription = YourSubscriptionHere
- api-version = 2021-04-01-preview

Headers:

- If-Match* = True

I did this as advised by support and I am free to publish again :)

**Comment by titan-khang** [comment]
Confirm that the

> I have a response from MS support: This might be due to pop-ups being enabled on the developer portal which is available there already but not yet fully supported (breaking the portal bascially).
> 
> Solution is to run a content delete call through here: https://learn.microsoft.com/en-us/rest/api/apimanagement/current-ga/content-item/delete?tabs=HTTP#code-try-0
> 
> Parameters:
> 
> * contentItemId* = main-menu-popup
> * contentTypeId = popup
> * resourceGroupName = YourResourceGroupNameHere
> * serviceName = YourServiceNameHere
> * subscription = YourSubscriptionHere
> * api-version = 2021-04-01-preview
> 
> Headers:
> 
> * If-Match* = True
> 
> I did this as advised by support and I am free to publish again :)

Confirm that it works. I can publish the portal again. Thank you very much, I'm on the verge that reset everything and redo again. This makes me feel it so unreliable when things like this happen though.

**Comment by malincrist** [comment]
Hello @titan-khang ,
I'm glad the workaround provided worked for you and we apologize for the inconveniences.
There is currently an on-going issue with the "popup" content type and we are working to fix it.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
