### ISSUE TITLE
Cannot disable "edit mode"

### ISSUE THREAD

**Issue by woeterman94** [Azure/api-management-developer-portal#2055]
## Bug description

I'm unable to close the edit mode and use the developer portal as a "normal" user.
![image](https://user-images.githubusercontent.com/5755057/210222498-180a3cb7-168d-49d0-9dcf-6724dc918797.png)

![image](https://user-images.githubusercontent.com/5755057/210222738-7ab38946-fb82-4209-bff7-7ff953fbad2d.png)

## Reproduction steps

1. Click the "developer portal" button on the APIM screen in Azure. Or navigate to the portal by using its url.
2. The portal is in "edit mode". Clicking on anything allows you to edit it.

## Expected behavior

There should be a way to close or leave the editor mode and use the portal as a normal user.

## Is your portal managed or self-hosted?

Managed

**Comment by ZarTrox** [comment]
The "Developer Portal" Button in Azure opens the edit mode of the DevPortal environment. On the Overview page in Azure try to click the link next to "Developer Portal URL". This should open the normal DevPortal.

(Sometimes there is an issue when the editor mode has been opened in the current session. Try to open it in incognito if there is any issue)

**Comment by woeterman94** [comment]
I cannot use incognito mode because then I have to login again. Can't you provide a button to "exit" edit mode?

**Comment by malincrist** [comment]
Hello @woeterman94 ,

As @ZarTrox pointed out, the "Developer Portal" button will open the Developer Portal in edit mode and, after you opened it in edit mode, the current session will still have the token for some time so whenever you access the Developer Portal, it will be in edit mode.

You can open it in incognito mode or you can clear the current session, if you want to use the developer portal in normal mode.

However, you can still navigate through and test the Developer Portal, even if you are in edit mode, by using `Ctrl + click` instead of normal click.

**Comment by woeterman94** [comment]
As said before: incognito mode is not an option. Because of the single sign on with Azure AD. Please ad a button to clear the token...Op 6 jan. 2023 14:10 schreef malincrist ***@***.***>:
Hello @woeterman94 ,
As @ZarTrox pointed out, the "Developer Portal" button will open the Developer Portal in edit mode and, after you opened it in edit mode, the current session will still have the token for some time so whenever you access the Developer Portal, it will be in edit mode.
You can open it in incognito mode or you can clear the current session, if you want to use the developer portal in normal mode.
However, you can still navigate through and test the Developer Portal, even if you are in edit mode, by using Ctrl + click instead of normal click.

**Comment by jsorohova** [comment]
Hello @woeterman94 , we are working on a new admin UI. It will improve your experience within the Developer portal, but the work in still in progress. Thank you for raising this issue.

**Comment by charan-vendra** [comment]
> Hello @woeterman94 , we are working on a new admin UI. It will improve your experience within the Developer portal, but the work in still in progress. Thank you for raising this issue.

Hi, has there been any progress on this.
It seems like this issue is massively nerfing user experience. Ideally the portal should open in normal mode and there should be an option to enable edit mode for admins.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

**Comment by woeterman94** [comment]
Hello @mrcarlosdev,

I don't get why you are closing issues that aren't even resolved. 
Feel free to merge / move / copy this issue to wherever you want. 

Thanks!

**Comment by danielhertzman** [comment]
Hello!

Here I am in March 2025 and have the same issue. I can't escape the editor mode and it really annoys me. What went wrong, API management?

**Comment by jsorohova** [comment]
Hello @danielhertzman, you can click Crtl+F10 to disable admin view. The topbar won't disappear for now, this is in our backlog, we'll pick it up ASAP.
