### ISSUE TITLE
Security Headers are missing in Developer Portal

### ISSUE THREAD

**Issue by MuhasseenaSajeed** [Azure/api-management-developer-portal#2062]
## Bug description
While testing the developer portal with Burp suite tool, we are getting the issues like below headers are missing

## Reproduction steps

1. Login to Developer Portal.
2. Capture random requests in Burp Suite.
3. It is observed that certain security headers are missing. 

    a)Host: ADB2C URL
        - Content Security Policy header is missing
    b)Host: Developer portal URL
        - Content Security Policy header is missing
    c)Host: API Management URL
        -X-Frame-Options, X-XSS Protection and Content Security Policy headers are missing.

## Expected behavior

All relevant security headers should be present

## Is your portal managed or self-hosted?

Managed 

## Environment

 - Operating system: Windows 11
 - Browser: Google Chrome

## Additional context

Add any other context about the problem here, including screenshots

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
