### ISSUE TITLE
Try It Out does not allow for multiple value selection for arrays with enums

### ISSUE THREAD

**Issue by redashimself** [Azure/api-management-developer-portal#2082]
## Bug description

When using the _Try It Out_ feature with enum query parameter, it's not possible to select multiple parameter values.
## Reproduction steps

1. In Azure API Management Portal, go to APIs
2. Define OpenAPI specification (JSON) to include an enum parameter:
```
   {
      "name": "TestParameter",
      "in": "query",
      "schema": {
          "enum": ["Value1", "Value2", "Value3"],
          "type": "array"
      }
  }
```
4. Save and go to the same API in Developer Portal
5. Click _Try It Out_
6. The added parameter should be visible and only one value can be selected, not multiple (see screenshot below):
![image](https://user-images.githubusercontent.com/114561058/216083966-78b7ff35-450b-4186-8e8d-5db7fd3637cb.png)

## Expected behavior

When using the _Try It Out_ feature with an array query parameter, multiple selection is allowed, and the query URL is formed appropriately e.g. `TestParameter=Value1, Value2`.

## Is your portal managed or self-hosted?

Managed

**Comment by iangithubusername** [comment]
Gosh this is a real problem for us too.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
