### ISSUE TITLE
Missing Validation for the field Email Id on sign up page and forgot password page

### ISSUE THREAD

**Issue by rajdeep1704** [Azure/api-management-developer-portal#2086]
## Bug description
When we are trying to sign up by entering the following 2 invalid email address specified in Wikipedia it's not validating and prompting any error message.
https://en.wikipedia.org/wiki/Email_address
**1234567890123456789012345678901234567890123456789012345678901234+x@example.com** (local-part is longer than 64 characters)
**i_like_underscore@but_its_not_allowed_in_this_part.example.com** (Underscore is not allowed in domain part)

## Reproduction steps

1. Go to 'Developer Portal'
2. Click on 'Sign Up'
3. Enter the email mentioned above in email id field and provide all valid values in other fields
4. Click on Sign up

## Expected behavior

It should validate for character limitation and invalid pattern for Email Id field and prompt error message respectively.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 11
 - Browser: Google Chrome

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
