### ISSUE TITLE
Weak Password Policy

### ISSUE THREAD

**Issue by rajdeep1704** [Azure/api-management-developer-portal#2087]
## Bug description

The default username and password option lack basic security features. I was able to set 12345678 as password.

## Reproduction steps

1. Go to 'Developer portal'
2. Click on 'Sign up'
3. Sign up using weak password i.e. give password value as 12345678
4. User is able to sign up with weak password

## Expected behavior

**Strong password policy should be implemented.**

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 11
 - Browser: Google Chrome

**Comment by mikebudzynski** [comment]
@rajdeep1704 What password policy would you expect?

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
