### ISSUE TITLE
Validation on Product Input Subscription Name field

### ISSUE THREAD

**Issue by rajdeep1704** [Azure/api-management-developer-portal#2090]
## Bug description

Whenever user tries to subscribe the product by entering any character/numeric value. System is accepting the user input. There was no validation for the field Input Subscription name.

## Reproduction steps

1. Go to 'Developer Portal'
2. Sign in using valid credentials
3. Go to products page and click on any specific product.
4. Try to subscribe the particular product by adding any of the name for e.g. "12345"

## Expected behavior

Either the name should be validated with some criteria or else it should be auto binded for the product name.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 11
 - Browser: Google Chrome

## Additional context

<img width="538" alt="MicrosoftTeams-image (8)" src="https://user-images.githubusercontent.com/124578301/217445303-32fb804b-bc08-4be7-9f68-9cf691d0201f.png">

**Comment by mikebudzynski** [comment]
@rajdeep1704 What's your concern? Why would we prohibit users from naming subscriptions the way they want to name them?

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
