### ISSUE TITLE
Immediate sign-out with redirect to sign-in page

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#2123]
## Bug description

In our environments when the sign-out menu item (with the link target `#signout`) is pressed nothing happens at first.
Only after switching through pages for some time the portal recognizes that the user wants to be/is signed out and forwards to the sign-in page.

Navigation item settings:
![image](https://user-images.githubusercontent.com/58420097/222373305-5f271710-b319-4aa7-94bb-2aadaf3a0df8.png)

## Reproduction steps

1. Add menu item with the settings in the screenshot
2. Publish revision
3. Sign in to the DevPortal
4. Click on the menu item
5. See that no forward to sign-in happens

## Expected behavior

The Portal should immediately forward the user to the sign-in page after clicking an element with the `#signout` link.
No waiting or extra clicking should be necessary. The signed out user should not have any access anymore to any page, which is currently possible.

## Is your portal managed or self-hosted?

Managed

**Comment by jsorohova** [comment]
Hello @ZarTrox , thank you for reporting the issue. Although, I can't reproduce it. When I click the Sign out button, the user is immediately signed out and redirected to the home page. Do you have all pages restricted for a signed in users only?

If you need more help, please, send us an email with your instance name to apimportalfeedback@microsoft.com.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
