### ISSUE TITLE
OpenID Connect - autorization_code

### ISSUE THREAD

**Issue by Hallgeir** [Azure/api-management-developer-portal#2135]
## Bug description
When trying to authenticate using openid connect with autorization code in developer portal i get this error message. 
(It works using implicit flow)
![image](https://user-images.githubusercontent.com/10558331/226378872-20c48896-422e-4754-aa92-633e7b6d7382.png)

Configuration of OpenID Connect in Developer portal. 
![image](https://user-images.githubusercontent.com/10558331/226383279-951ca018-a1bd-4e96-a925-85ebd92124c6.png)
As you can see from the metadata endpoint, I'm using a b2c tenant, but not sure if that is relevant. 

## Reproduction steps

1. Set up B2C Tenant
2. Register an App Registration with correct redirect uri's
![image](https://user-images.githubusercontent.com/10558331/226384491-ba431c13-9116-40aa-af90-fb29a7010e59.png)
4. Setup OpenID Connect with API Management in Azure
5. Try an api in Developer Portal using Autorization Code Flow

## Expected behavior

You should receive and access token 

## Is your portal managed or self-hosted?

Managed 

## API Management service name

NorsvinAPIManagement

## Environment

 - Operating system: Window 10
 - Browser: Google Chrome, Microsoft Edge

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
