### ISSUE TITLE
Text styling issues when using `Ctrl + a` to select the text

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#2165]
## Bug description

When editing text widgets it is sometimes necessary to highlight the whole text to define text alignment.
As using left click and dragging the mouse across the text field sometimes moves the whole text widget into a different section (if not careful enough) one has to use the `Ctrl + a` shortkey to select everything in the text element.

When trying to apply styles to the selected text with the shortkey it does not work and even creates some more issues.
Resetting previous styling, not applying new styling and showing that the new styling is set but not applied:

![2023-04-28_10-43-24](https://user-images.githubusercontent.com/58420097/235101576-b1b317f6-2915-4bf2-bfd7-1b5ad85604e9.gif)

## Reproduction steps

1. Create new page
2. Click into the default text widget
3. Select the text by pressing `ctrl + a`
4. Change the text alignment

## Is your portal managed or self-hosted?

Managed

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
