### ISSUE TITLE
Operation names not visible

### ISSUE THREAD

**Issue by sknijn** [Azure/api-management-developer-portal#2217]
## Bug description

A clear and concise description of the bug.

## Reproduction steps

1. Go to 'APIs.'
2. Select an API
On the left are the Operations and on the right all details for each Operation
When the Operation Name is too large, it gets truncated and we see only the first 47 characters

## Expected behavior
It would be really helpfull if he seperator bar between Operations on the left and Operation Details on the right would be sizable; that you can extend the Operations column to see all details.

## Is your portal managed or self-hosted?
Managed 

## API Management service name
vivat-apim-prd

## Environment
 - Operating system: Windows 10
 - Browser: Microsoft Edge
 - Version: 114.0.1823.51

## Additional context
![screenshot](https://github.com/Azure/api-management-developer-portal/assets/49560751/810181da-7a19-4397-b1d0-ee2388e6c77a)

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
