### ISSUE TITLE
Home page background section unselectable / UI widgets missing

### ISSUE THREAD

**Issue by boulajp** [Azure/api-management-developer-portal#2234]
## Bug description

The home page background image is not changable as that section cannot be selected as the Azure API Management video [here ](https://www.youtube.com/watch?v=5mMtUSmfUlw) described.

## Reproduction steps

1. Go to Pages
2. Click on Home
3. Attempt to select the background image
4. See that the "edit section" UI elements are missing

![image](https://github.com/Azure/api-management-developer-portal/assets/10444504/b45aeb3a-2871-4930-b037-08e3c76cdc25)

## Expected behavior

The background image section should be selectable and display these widgets:

![image](https://github.com/Azure/api-management-developer-portal/assets/10444504/a360babb-3e23-4097-a374-864381bfd72a)

## Is your portal managed or self-hosted?

Managed

## API Management service name

testpublicapijoboulan

## Environment

 - Operating system: Windows 10
 - Browser: Google Chrome, Edge

**Comment by javierbo1989** [comment]
Hi boulajp, to edit the Home page background section, you have two options: either double-click directly on that section, or click on it once to bring up a small menu that includes the option 'Edit Section'. Please don't hesitate to let us know if you require any further assistance. Thank you.
![image](https://github.com/Azure/api-management-developer-portal/assets/88548172/556f905b-bfc9-4ad3-af90-fb9b8fbfe908)

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
