### ISSUE TITLE
Referrer-Policy Not Implemented

### ISSUE THREAD

**Issue by Harmanpreet-96** [Azure/api-management-developer-portal#2256]
## Bug description

Security scan detected that no Referrer-Policy header implemented.

Referrer-Policy is a security header designed to prevent cross-domain Referer leakage.

Impact
Referer header is a request header that indicates the site which the traffic originated from. If there is no adequate prevention in
place, the  URL itself, and even sensitive information contained in the URL will be leaked to the cross-site.
The lack of Referrer-Policy header might affect privacy of the users and site's itself

## Expected behavior

Please implement a Referrer-Policy by using the Referrer-Policy response header or by declaring it in the meta tags. It’s also
possible to control referrer information over an HTML-element by using the rel attribute.

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

[e.g., release `2.0.0`, commit `c45da9778b70d369aba60fa2e63c191efe2b548f`]

## API Management service name

enterprise-apim-dev

## Environment

 - Operating system: [e.g., iOS]
 - Browser: [e.g., Google Chrome, Safari]
 - Version: [e.g., 22]

## Additional context

Add any other context about the problem here, including screenshots.

**Comment by malincrist** [comment]
Hello  @Harmanpreet-96,  thank you for bringing this issue to our attention. We have created an internal work item to investigate and address this.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
