### ISSUE TITLE
API Version drop down is not visible on Self hosted portal

### ISSUE THREAD

**Issue by sjvarun** [Azure/api-management-developer-portal#2354]
**Every bug report should have precise description and reproduction steps; console traces or source code references are appreciated.**

**For assistance requests, contact Azure support or submit a post [on Stack Overflow](http://aka.ms/apimso). We don't provide support through GitHub Issues. Feature requests can be raised [on the Azure Feedback Forum](https://aka.ms/apimwish).**

## Bug description

API Version drop down is not visible on Self hosted portal, but it is visible on managed portal

## Reproduction steps

1. Go to API List page 
2. Click on any API that has more than 1 version
3. On the API Details widget where the api version drop down should is shown in managed portal
4. This same api version drop down is not visible on Self hosted portal

## Expected behavior

API version drop down must be visible on self hosted portal as well

## Is your portal managed or self-hosted?

 Self-hosted

## Release tag or commit SHA (if using self-hosted version)

release `2.23.0`

## API Management service name

hapidev

**Comment by malincrist** [comment]
Hello @sjvarun , thanks for reaching out.
I am not able to reproduce the issue you described. 
I am also unable to find any service with the name 'hapidev', to check it.

Could it be the same issue as #2201 ? For this one, it only happens if you have 100+ apis (including both apis and api versions together), and the dropdown is not visible for the apis which should be on the second page (for example the 101st api, 102nd api, etc.)
This is a known issue, that is fixed for the managed portal and the fix will be added in the self-hosted as well. However, we don't have an ETA for it.

**Comment by sjvarun** [comment]
@malincrist Yes this is same issue as https://github.com/Azure/api-management-developer-portal/issues/2201.
Thanks for your reply

**Comment by annaji-msft** [comment]
duplicate of https://github.com/Azure/api-management-developer-portal/issues/2201
