### ISSUE TITLE
CORS - since the browser initiates the request, it requires Cross-Origin Resource Sharing (CORS) enabled on the server.

### ISSUE THREAD

**Issue by dwall123** [Azure/api-management-developer-portal#290]
Unable to use the new developer portal to send requests to APIM instance using 'Try It' functionality as the following message occurs.

"Since the browser initiates the request, it requires Cross-Origin Resource Sharing (CORS) enabled on the server."
I have set the CORS policy in the APIM Inbound section to allow all. 

**To Reproduce**
- Navigate to the developer portal for a new APIM instance.
- Set the CORS policy for Inbound on the Echo API
- Use 'Try it' on any of the operations in the default 'Echo API'
**Expected behavior**
Request should be sent to the backend API
**Portal environment**
Managed 

**Environment**
Browser: Chrome

**Comment by mikebudzynski** [comment]
Make sure you have specified the policy correctly, including allowed methods and headers. For example

```XML
<cors>
            <allowed-origins>
                <origin>*</origin>
            </allowed-origins>
            <allowed-methods>
                <method>GET</method>
                <method>POST</method>
                <method>PUT</method>
                <method>DELETE</method>
                <method>HEAD</method>
                <method>OPTIONS</method>
                <method>PATCH</method>
                <method>TRACE</method>
            </allowed-methods>
            <allowed-headers>
                <header>*</header>
            </allowed-headers>
            <expose-headers>
                <header>*</header>
            </expose-headers>
        </cors>
```

If you're still having problems, please contact Azure support.

**Comment by davidjsteele** [comment]
Also seeing this issue with the above policy in place, are you positive this is not a bug?

**Comment by mikebudzynski** [comment]
@davidjsteele Can you please check if you applied the policy on the right scope (inbound for all operations in an API)?

**Comment by davidjsteele** [comment]
@mikebudzynski Thanks for coming back to me so quickly.  The policy has been applied on the <inbound> scope at a product level and the API is associated with that product.   

Bit more investigation; the browser error does indeed suggest a CORS issue as is initiating a pre-flight request with OPTIONS
![image](https://user-images.githubusercontent.com/7621977/68935844-2889e700-0791-11ea-934e-4c0fc884bf40.png)
 And the error is as per 
{ "statusCode": 401, "message": "Access denied due to **missing** subscription key. Make sure to include subscription key when making requests to an API." }

With the Ocp-Apim-Subscription-Key being set I'd expect this to pass through

![image](https://user-images.githubusercontent.com/7621977/68935996-71da3680-0791-11ea-8eea-26c5dfd93b62.png)

**Comment by mikebudzynski** [comment]
@davidjsteele I'll reopen this issue and we'll investigate the problem. In future please open a separate issue.

**Comment by azaslonov** [comment]
Hi @davidjsteele, the legacy, portal works through proxy service. We'll add this option, in addition to direct browser calls in nearest future.

**Comment by mikebudzynski** [comment]
@davidjsteele Can you confirm:

1. Your subscription key is part of the Product, which has the CORS policy
1. You're using the correct header for the subscription key (the header may be in the top section of the console)

If that still doesn't resolve your problem, you can email us with precise reproduction steps and the name of your service at apimportalfeedback@microsoft.com

**Comment by davidjsteele** [comment]
Thanks @mikebudzynski - have replied by email.

**Comment by mikebudzynski** [comment]
Upon further investigation - this behavior exists by design.

The OPTIONS call is automatically issued by the browser and it doesn’t contain a header with the subscription key. Because API Management doesn't receive the subscription key, it can’t associate the OPTIONS call with a Product, so it can’t apply the CORS policy.

There are two workarounds:
-	Pass the subscription key in a query parameter instead of a header (not advised from a security standpoint)
-	Apply the CORS policy on an API/API operation/global level

I'll update the documentation to mention this scenario.

**Comment by dgrospelier** [comment]
@mikebudzynski: we have the same issue on our APIM instance.
When we apply this policy at the "All APIs" level, it is not working. It is working only when we apply the policy at the API level or API Operation level. Is it a bug?

**Comment by ryanlifferth** [comment]
I had a similar issue with this.  I was unable to get the querystring workaround to work properly.  However, it did work when I added the policies --> inbound section of API Management service policies `<set-header name="Ocp-Apim-Subscription-Key" exists-action="delete" />`.

Without this setting, I continue to get CORS error on my POST, but not on the OPTIONS call.  My question is, is the expected behavior and does this solution follow expected pattern for APIM subscription key usage?

**Comment by gaurav-p-sood** [comment]
> I had a similar issue with this. I was unable to get the querystring workaround to work properly. However, it did work when I added the policies --> inbound section of API Management service policies `<set-header name="Ocp-Apim-Subscription-Key" exists-action="delete" />`.
> 
> Without this setting, I continue to get CORS error on my POST, but not on the OPTIONS call. My question is, is the expected behavior and does this solution follow expected pattern for APIM subscription key usage?

Hi Ryan

Despite implementing it , I could not make it work . I have tried to allow CORS on Operation/API and finally at Product level , still doenst work . Any Suggestions ? 

Regards
Gaurav

**Comment by dersia** [comment]
This is still an issue as of today. Event if I add an policy for the cors headers, there is still the issue, if the API is missing an OPTIONS operation, so the preflight always fails with a 404. I think this issue needs to be reopened.

@mikebudzynski the documentation is also gone and not available anymore.

**Comment by mikebudzynski** [comment]
You can use the CORS proxy feature: https://docs.microsoft.com/en-us/azure/api-management/developer-portal-faq#what-is-the-cors-proxy-feature-and-when-should-i-use-it

**Comment by dersia** [comment]
@mikebudzynski sounds great, where can I find that option? Either I am not seeing it or it's hidden really well :)

**Comment by mikebudzynski** [comment]
You have to click on the API operation details widget in the admin mode and select the "Pencil" icon to see the pop-up with the options.

**Comment by dersia** [comment]
@mikebudzynski wow, that was hard to find, but it does work, thanks! 😉

**Comment by m-adami** [comment]
Hello,

I'm still unable to call my APIs from the Developers' portal.

My API has a CORS policy, which inclused the URL of the developer's portal:

![api_cors_policy](https://user-images.githubusercontent.com/98111423/225871748-ba49f4e4-5b91-46d0-b324-75bc147276c1.png)

I have enabled CORS proxy in the API I'm testing:

![apim_cors_proxy](https://user-images.githubusercontent.com/98111423/225871823-b119ea9b-d5d6-4265-8e2a-50951aaf58d6.png)

When I try to call my API from the Developers' portal, I get:


![APIM_CORS_error](https://user-images.githubusercontent.com/98111423/225871895-894fdb9c-a8c8-482b-9179-ef9cb48911e4.png)

In the network tab of my browser, I can see a 404 error when calling the API with the OPTIONS method:


![apim_options_404](https://user-images.githubusercontent.com/98111423/225872056-187e93cb-955f-4bc9-afa6-e192bbe9d35a.png)

Any idea how I can solve this without having to explicitly add the options method to all my APIs?

thanks,

Marco

**Comment by prasadkkaranth** [comment]
I am not sure if its relevant in your case, but I faced the same problem in APIM Developer Portal today.. One of the backend Developer asked me to update their swagger, so I went ahead and updated it. That's when I started getting this error: "Unable to complete the request. Since the browser initiates the request, it requires Cross-Origin Resource Sharing (CORS) enabled on the server.". After trying few things, I noticed that URL Scheme was changed to HTTP, instead of HTTPS.. I corrected it and it fixed the problem. His Swagger had: "schemes":["http"]

![image](https://github.com/user-attachments/assets/5f742496-c8e5-4197-a13d-0b769bd0e137)
