### ISSUE TITLE
Funky behavior when running on different port

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/api-management-developer-portal#291]
**Describe the bug**
We're running the portal as part of a Docker container that is exposed on `:8899` but the links to other pages no longer work then.

While the link adapts, for example `http://localhost:8899/apis` but in the end it will redirect to `http://localhost/apis`.

**To Reproduce**
1. Create Docker image, ([example](https://github.com/CoditEU/microservices-with-azure-api-management-webinar/blob/master/deploy/api-management/dev-portal/Dockerfile))
2. Expose on other port via `docker run -d -p 889`
3. Navigate to other page

**Expected behavior**
Initial port is respected

**Portal environment**
Self-hosted

**Release tag or commit SHA (if using self-hosted version)**
Preview, might be outdated but want to verify

**Environment**
 - Operating system: Linux container
 - Browser: Chrome & Edge preview

**Comment by azaslonov** [comment]
Hi Tom, are we talking about the published version of the portal or you're running webpack development server in your container?

**Comment by tomkerkhove** [comment]
We are using the published output which you can find in the sample mentioned above.

Do note that this was before GA but don't have source anymore so not sure how to find the version.

**Comment by tomkerkhove** [comment]
Just wanted to report to verify that this is fixed or not.

**Comment by mikebudzynski** [comment]
@tomkerkhove Thanks for reporting the problem, we'll investigate it and come back to you. It may take a while as we're working on other, high-priority issues at this moment.

**Comment by ygrik** [comment]
Hi @tomkerkhove 
The problem is in **Nginx** configurations and how it works with trailing **/**
For example, if you click a button with ref="/apis" 
**Nginx** redirects the request to "/apis/" but Nginx does not know that you run the container on 889 port and redirects to http://localhost/apis/
You can find more info by this link 
https://stackoverflow.com/questions/15555428/nginx-causes-301-redirect-if-theres-no-trailing-slash
