### ISSUE TITLE
Unable to view API in the Developer Portal

### ISSUE THREAD

**Issue by sethwenzel** [Azure/api-management-developer-portal#295]
**Describe the bug**
Unable to browse an API on the new API-M Developer Portal.  After clicking on the API from the API list, we briefly see the API's methods, then about 1-2 seconds later are redirected to a 500 error page.

**To Reproduce**
1. Sign in to the API-M Developer portal as a user
2. Click on APIs
3. Click the API you want to see
4. See error (seems to be trying to load the operations maybe)

**Expected behavior**
We expect to see the API's operations, and test them

**Portal environment**
Managed

**Release tag or commit SHA (if using self-hosted version)**
This is Managed, not sure how to tell you the commit tag?

**API Management service name**
apim-edge-dev

**Environment**
 - Operating system: [e.g., iOS]
 - Browser: Edge chromium dev
 - Version: Version 80.0.320.4 (Official build) dev (64-bit)

**Additional context**

![Annotation 2019-11-08 080822](https://user-images.githubusercontent.com/2038137/68479409-43dc7b80-0200-11ea-8a5e-d99113883d97.png)

**Comment by AdrianSanguineti** [comment]
I've managed to reproduce the conditions which cause this error to occur. It appears to be occur whenever an operation has a response representation defined.

The steps I used to recreate the bug is:

1. Create a new blank API through Azure Portal
2. I added it to the default `unlimited` product to let me see the API published as anonymous user.
3. Create a new GET operation, name it anything and fill in all required fields.
4. Under the responses tab, add 200 OK response. **Leave everything blank for now**
4. Go to the new developer portal (managed).
5. Make sure the new API is visible, and that you can browse the GET operation without errors.
6. Back in the Azure Portal, edit the GET operation.
7. Under the responses tab, click the `+ Add Representation` button.
8. Type in `application/json` and select the matching result _(FYI - Unrelated bug but this search box does not appear to initialise with values you can select until after you type something. Very non-intuitive.)_
9. Leave Sample blank
10. Click the `Select Definition` box and click `+ New` button.
11. Paste following into the `Payload` box:
```json
{
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "id": {
            "type": "string"
        }
    }
}
```
12. Give the representation any name you wish.
13. Save the operation.
14. Go back to the new developer portal and try to via the API again -> **_redirects to /500_**
15. Remove the response representation from the operation.
16. Go back to the new developer portal and try to via the API again -> **_no  errors_**

I haven't tried this with an API that I import from a swagger/openapi definition that includes representations yet (most of my APIs do), as I have only been playing around in a blank dev APIM instance to get a feel for the new portal. But I have a feeling this bug might exist in that scenario too.

**Comment by AdrianSanguineti** [comment]
Curiosity has gotten the better of me and I've investigated the error further myself. It looks like the expected `SchemaContract` in the portal's code does not match the response that the schemas operation return in the management API:

```json
{
  "id": "/subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.ApiManagement/service/xxx/apis/awesomo-v2/schemas/1573267190751",
  "type": "Microsoft.ApiManagement/service/apis/schemas",
  "name": "1573267190751",
  "properties": {
    "contentType": "application/vnd.oai.openapi.components+json",
    "document": {
      "components": {
        "schemas": {
          "MyResponse": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "id": {
                "type": "string"
              }
            }
          }
        }
      }
    }
  }
}
```

[Line 10 of models/schema.ts](https://github.com/Azure/api-management-developer-portal/blob/master/src/models/schema.ts#L10) is expecting the response to be structured:

`contract.properties.document.definitions`

whereas it should be: 

`contract.properties.document.components.schemas`.

I _hacked_ the following changes together in my local dev to `contracts/schema.ts`:

```
/**
 * 
 */
export interface SchemaDocumentContract {
    components: Bag<SchemaComponentsContract>;
}

// NEW CONTRACT INTERFACE
export interface SchemaComponentsContract {
    schemas: Bag<SchemaObjectContract>;
}

/**
 * 
 */
export interface SchemaContract extends ArmResource  {
    properties: {
        contentType: string;
        document?: SchemaDocumentContract;
    };
}
```

And updated lines 10-16 of models/schema.ts to:
```javascript
if (contract.properties.document && contract.properties.document.components && contract.properties.document.components.schemas) {
    this.definitions = Object
                .keys(contract.properties.document.components.schemas)
                .map(definitionName => {
                    return new TypeDefinition(definitionName, contract.properties.document.components.schemas[definitionName]);
                });
}
```

Lines 24 of models/schema.ts also had to be updated to reflect the contract change:

```javascript
export class SchemaDocument {
    public definitions?: Object;

    constructor(contract: SchemaDocumentContract) {
        // Old
        this.definitions = contract.definitions;

        // New
        this.definitions = contract.components.schemas;
    }
}
```

Once I made the changes, the error stopped and the representations appeared on page.

I'm not setup right now to make this changes properly in a branch and submit a PR (only just cloned the repository for the first time today). So someone else can feel to have a go and fixing the issue in the source.

I also feel like there are perhaps some missing integration tests that could have caught this mismatch before the current version of the portal was released. Given that area looks extremely sparse right now, perhaps this is an opportunity for improvement.

**Comment by azaslonov** [comment]
Hi @sethwenzel, @AdrianSanguineti (thanks for investigation!), thank you for reporting the issue.

I believe we don't distinguish properly between OpenAPI 2.0 (Swagger) and OpenAPI v3.0. We'll have a closer look into it and fix it. I'll update the thread once it's done.

**Comment by sethwenzel** [comment]
@azaslonov & @ygrik - this is happening again, but with a new error, only if it's openapi 3.0. 

`TypeError: "this.definition is undefined"
    initialize webpack:///./src/components/operations/operation-details/ko/runtime/type-definition.ts?:41
    node_modules paperbits/core/ko/knockout.loaders.ts?:74
    node_modules paperbits/core/ko/knockout.loaders.ts?:71
    c webpack:///./node_modules/knockout/build/output/knockout-latest.js?:91
    node_modules paperbits/core/ko/knockout.loaders.ts?:108
    node_modules paperbits/core/ko/bindingHandlers/bindingHandlers.component.ts?:106
    node_modules paperbits/core/ko/bindingHandlers/bindingHandlers.component.ts?:57
    notifySubscribers webpack:///./node_modules/knockout/build/output/knockout-latest.js?:41
    c webpack:///./node_modules/knockout/build/output/knockout-latest.js?:89
    b webpack:///./node_modules/knockout/build/output/knockout-latest.js?:37
    c webpack:///./node_modules/knockout/build/output/knockout-latest.js?:37
consoleLogger.ts:61:25
TypeError: this.definition is undefined`

**Comment by ygrik** [comment]
@sethwenzel we did not deploy this fix to the managed version. Planning to deploy the fix this week.
