### ISSUE TITLE
Subscription Key not present in the "try-it" pane

### ISSUE THREAD

**Issue by KevinBacas** [Azure/api-management-developer-portal#332]
I tried the new Azure Developer portal. When I log in and browse the API, I'm unable to try to call it from the portal because the field **Subscription key** is not provided :
![image](https://user-images.githubusercontent.com/1434393/69262197-5755f200-0bc3-11ea-9055-67f6910ee7da.png)

Is there a way to fill this field automatically so users can try the API as we have in the legacy developer portal?

cc @dgrospelier

**Comment by azaslonov** [comment]
Hi @KevinBacas, thank you for reporting the issue.

Since you see keys in the old developer portal, but not in the new one, can you please check couple of things:
- you're signed in as a developer user (not admin) and you have a subscription to a product containing this API.
- in the old portal (when you see keys), you're not logged in as admin.

If you still think there is an issue after that, please email us your service name to apimportalfeedback@microsoft.com, we'll be happy to look further into it.

**Comment by erbg** [comment]
Hi,

I confirm the problem reported. In the new portal, allthow the subscription key is provided in the Subscription field, it is not valorized in the Header:

The Ocp-Apim-Subscription-Key is valorized with "undefined".

![image](https://user-images.githubusercontent.com/23281925/69453430-2e209780-0d64-11ea-924c-d09940a44d5e.png)

**Comment by mikebudzynski** [comment]
@erbg 

1. Is it in the published portal?
2. Could you please send us your service name to apimportalfeedback@microsoft.com and indicate the user and the API for which the problem manifests?

**Comment by azaslonov** [comment]
Hi @erbg, 

The issue with subscription in question here is the scope, currently, it is set to `All APIs`, which new portal doesn’t support just yet. I have filed a separate issue for tracking it: #339.
