### ISSUE TITLE
Changed subscription key header name not being used on the 'try it' page

### ISSUE THREAD

**Issue by pedwards1** [Azure/api-management-developer-portal#341]
Hi,

I've deployed a new instance of APIM with the managed developer portal. A single test API has been added (an Azure function) which I was able to 'try' successfully from the dev portal (GET/POST).

Having changed the subscription key name however at API level (The 'header name' under 'subscription' on the 'settings' tab of the API) i'm experiencing an issue.

The new subscription key header name is 'subscription-key' however the dev portal 'try it' tab is defaulting the header to 'Ocp-Apim-Subscription-Key'. I can see when the dev portal loads the API data on page load it is indeed showing that the subscription key name is correct i.e.

`    "subscriptionKeyParameterNames": {
      "header": "subscription-key",
      "query": "subscription-key"
    },`

this is not reflected in the UI however.. I can change this header name manually in the UI and successfully submit the test which calls the API without error.

**Comment by yinlaurent** [comment]
## Bug description

Hello, I have the same issue and was a bit late on the post :).

I modified the name of the APIM subscription key header to "Apim-Subscription-Key". In the previous developer portal, it was displayed correctly but in the new developer portal, the name of the header remains Ocp-Apim-Subscription-Key.
Consequently, basic calls from the new developer portal fall in error.

Does the new portal take the custom subscription header name into account?

## Reproduction steps

1. Modify the name of the Subscription header of an existing API, in the API Settings tab.
<img width="406" alt="APIM Subscription Header name" src="https://user-images.githubusercontent.com/6747194/69653303-44d03280-1073-11ea-8b17-ac4578cde67b.png">

2. Go to the new developer portal and select the API.
3. Go to an operation and click on the Try it button.
4. The header name is "Ocp-Apim-Subscription-Key" instead of the name set on step 1.
<img width="699" alt="APIM New portal headers" src="https://user-images.githubusercontent.com/6747194/69654029-6847ad00-1074-11ea-9134-849a7861a8f7.png">


## Expected behavior

The header name set on step 1, like in the previous portal.
<img width="601" alt="APIM Previous portal headers" src="https://user-images.githubusercontent.com/6747194/69654041-6bdb3400-1074-11ea-82b0-ff8e1034465c.png">


## Is your portal managed or self-hosted?

Managed


## Environment

 - Browser: Google Chrome, Edge

## Additional context

**Comment by azaslonov** [comment]
Hi @pedwards1, @yinlaurent, thank you for reporting the issue, we'll address it.

**Comment by pedwards1** [comment]
This still appears to be unresolved - the header is defaulting to 'Ocp-Apim-Subscription-Key' on the try it page, even though my API is configured to use 'subscription-key'. I am using the managed portal and as far as i'm aware the fix for this was released in december.

**Comment by azaslonov** [comment]
Hi @pedwards1, I just tried again on one of the production services, and it appears to be working:

![image](https://user-images.githubusercontent.com/2320302/73293978-bb93c400-41b9-11ea-84b3-ab4200bdc8c8.png)

![image](https://user-images.githubusercontent.com/2320302/73294065-ebdb6280-41b9-11ea-9be8-769ce13f3e4a.png)


Please check again that the config is correct, and if the issue persists, please send your service name to apimportalfeedback@microsoft.com, we'll take a closer look.

**Comment by mikebudzynski** [comment]
Also, make sure you republish your portal.

**Comment by pedwards1** [comment]
Thanks - i've republished the dev portal and the fix is now working as expected.. I wasn't aware that i'd have to publish dev portal changes.

**Comment by azaslonov** [comment]
Great! Thanks for confirming it.
