### ISSUE TITLE
REST API documentation

### ISSUE THREAD

**Issue by jonatanP1993** [Azure/api-management-developer-portal#364]
Hi, I am trying to create a DevOps pipeline to move the Developer portal templates between our environments (dev -> test -> prod), but I am having some issues finding the reference documentation for the REST API.

Tried finding it at:
- https://github.com/Azure/api-management-developer-portal/wiki
- https://docs.microsoft.com/en-us/rest/api/apimanagement/

But I can't find the api-version referenced in the [scripts](https://github.com/Azure/api-management-developer-portal/tree/master/scripts).

I apologize if this is the wrong place to post this issue, and please point me in the right direction :)

Best Regards,

Jonatan

**Comment by azaslonov** [comment]
Hi Jonatan,

I guess you're looking for Content API used by those scripts? If yes, you can find it [here](https://github.com/Azure/api-management-developer-portal/wiki/Content-management-REST-API). 

Also, the version you're referring to (2018-06-01-preview) is still with `-preview` suffix, mainly because it yet to be documented. Please refer to #300 for tracking.
