### ISSUE TITLE
API Gallery - List of APIs widgets - dynamic links to the APIs are wrong 

### ISSUE THREAD

**Issue by stephanieberl** [Azure/api-management-developer-portal#372]
## Bug description

In both widgets "List of APIs" and "List of APIs title" the dynamic link is not working / incorrect and do not refer to the "API reference" page.

## Reproduction steps

1. Go to API Gallery
2. Add the widget "List of APIs"
3. Save and publish the page
4. Open the page in the "published" mode
5. Use the Hyperlink for one API --> Result: Nothing happens 

## Expected behavior

The hyperlink opens the "API Reference" Page of the selected API

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system:  WIN 10
 - Browser:  Google Chrome 
 - Version: 77.0.3865.90

## Additional context

Recommendation for correct link: 
https://dcs-apim-dev.developer.azure-api.net/**reference**#api=_APINAME_

**Comment by azaslonov** [comment]
Hi @stephanieberl,
Just in case, have you tried to set the URL on API list itself?
![image](https://user-images.githubusercontent.com/2320302/70937887-ff5faf00-1ff9-11ea-954c-3f31f14a8738.png)

**Comment by stephanieberl** [comment]
Yes i did - but why is the default value doing NOTHING - the user experience is more than strange in this case and there ist nowhere a hint to change the Link in the "edit" mode.

**Comment by azaslonov** [comment]
Hi @stephanieberl, thanks for the feedback.

The `default value` here means redirect to the same page, e.g. If you place API list and API details onto one page, clicking on items in API list would trigger selection in API details. Same way operation list and operation details have been setup in our default template.

The issue you describe was there in the default template at some point, I believe you were unlucky to create your service at that time. We do constantly update/fix that template, but once you created the website, we can't apply fixes to existing data, because we can override your changes inadvertently.

We surely understand your frustration and will be looking into improving the usability. Please also feel free to suggest or provide feedback on any question, we would greatly appreciate it.
