### ISSUE TITLE
List of Operations not refreshing on API selection until page refresh

### ISSUE THREAD

**Issue by zane-woodard-drc** [Azure/api-management-developer-portal#387]
Hello,
I have observed a bug with the currently live version of APIM developer portal in Azure where operations are failing display on first load, but display after refreshing the page.

My setup has multiple top level APIs configured, each with multiple operations under them. They're all tagged by the name of the top level API that they're under.
My APIM page has "List of APIs", under which there is a "List of Operations". To the right of both is the "Operations Details" widget.

## Bug description

When I first load the page, the List of APIs displays correctly and the List of Operations correctly displays as "No operations found". When I select an API from the List of APIs, the List of Operations does not update and continues to display "No operations found". It's only when I F5 the page  that the operations list correctly displays. One the page has been refreshed, I can freely click different APIs and the operations list will update.
When I navigate to another page and then back, the bug occurs again until I refresh the page.

## Reproduction steps

1. Go to the API reference page (or any page with List of APIs + List of Operations)
2. Click on an API
3. Observe the List of Operations remains unchanged, but the page URL is updated
4. F5 refresh the page, notice the List of Operations now populates

## Expected behavior

The List of Operations widget should display the operations for the currently selected API without needing to refresh the page.

## Is your portal managed or self-hosted?
Managed

## API Management service name

drc

## Environment

 - Operating system: Windows 10 OS Version 1809 (Build 17763.914)
 - Browser: Google Chrome
 - Version: 79.0.3945.79 (Official Build) (64-bit)

**Comment by azaslonov** [comment]
Hi @zane-woodard-drc, thanks for reporting the issue. We'll take care of it.

**Comment by ygrik** [comment]
Hi @zane-woodard-drc, 
I can't reproduce it, could you please send more details like the service name, API names on apimportalfeedback@microsoft.com

Does this issue exist in the editor or on the published site?

**Comment by zane-woodard-drc** [comment]
Hey @ygrik, just sent an e-mail with the service name and a link to our portal where you should be able to reproduce the issue.

The issue seems to happen in both the editor and the published site.

**Comment by ygrik** [comment]
The issue is not a bug and happens because you did not allow to make a selection to Operation list widget.
When you select an API, API list widget select API and Operation list do nothing because you did not allow to make a selection.
Just open editor for Operation list widget, check option Allow selection and publish.

**Comment by zane-woodard-drc** [comment]
Hello @ygrik,
I made that change for both Operations List and API List and published and the issue persists. If I remember correctly, we have experimented with that setting previously to try and fix this.

Inspecting the DOM seems to indicate the allowSelection = true setting was successfully changed and published, so it doesn't seem like some caching issue that I'm still seeing.

**Comment by travich** [comment]
FYI, I'm  having the same issue - but even the refresh doesn't work for me.  zane-woodard-drc did you ever solve this for yourself?

**Comment by zane-woodard-drc** [comment]
> FYI, I'm having the same issue - but even the refresh doesn't work for me. zane-woodard-drc did you ever solve this for yourself?

I was not able to resolve it with the provided solution or any other fix. I haven't gotten any response back after saying the provided solution doesn't fix the reported issue either.

**Comment by mikebudzynski** [comment]
@zane-woodard-drc can you confirm that:

1. You've updated to the latest release (if you use self-hosted portal)
2. You've provided the link to the page in the widget configuration
3. You've saved changes
4. You've republished your portal

**Comment by travich** [comment]
@ygrik  and @azaslonov  I'm glad to provide whatever you need to see how this issue is occurring.

**Comment by zane-woodard-drc** [comment]
@mikebudzynski 
> 2. You've provided the link to the page in the widget configuration
This seems to have solved the issue by triggering a full page reload when I click a link in the "List of APIs", which gets rid of the need to refresh the page.

My question now, if you don't mind, is why does the widget need to be configured to link to the page that contains it? There's nothing in the info bubble that explains this and it seems pretty non-intuitive. Shouldn't the widget be aware of what page it's on and thus what page needs to be linked to? What would be the use of something like a "List of APIs" widget that links to a different page than the one that contains it?

Thanks!

**Comment by mikebudzynski** [comment]
> My question now, if you don't mind, is why does the widget need to be configured to link to the page that contains it? 
> Shouldn't the widget be aware of what page it's on and thus what page needs to be linked to? What would be the use of something like a "List of APIs" widget that links to a different page than the one that contains it?

An example of it is in the default content that gets provisioned with your portal. There's a page with a list of all APIs and once you click on an API, you're redirected to an API reference page for that API (a separate page). The widget can't intelligently deduce what page to redirect to, because you can manipulate the pages in the portal however you wish.

> There's nothing in the info bubble that explains this and it seems pretty non-intuitive. 

That's something that we're planning to address.

**Comment by TravisLRiffle** [comment]
@mikebudzynski  I am self-hosting FWIW.  What I am seeing is that the APIs are dynamically showing up in the list of APIS for the admin site but not for the published developer site.  I've went entirely through generate.bat, run, publish, upload steps mentioned here: 
https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal

I have also made sure "allow selection" was checked.  Nothing I do at all will refresh with new API information.  From my observation there appears to be something about being an admin .vs a developer that keeps them from refreshing.  Is there a step or setting that I need to triple check to make sure the refresh happens as it should?  

What's important for my client is that the API information dynamically regenerate.  I have see the typescript code that calls out to 
`apis?expandApiVersionSet=true&$top=50&$skip=0&api-version=2018-06-01-preview `
and the URL being called is exactly the same (including to the API M instance) but getting different results.  I can only deduce that this is because of admin vs. developer mode.  

Hope this information helps - I have spent two days on this issue now and hope I can get some insight.

**Comment by TravisLRiffle** [comment]
> @mikebudzynski I am self-hosting FWIW. What I am seeing is that the APIs are dynamically showing up in the list of APIS for the admin site but not for the published developer site. I've went entirely through generate.bat, run, publish, upload steps mentioned here:
> https://github.com/Azure/api-management-developer-portal/wiki/Self-hosting-the-portal
> 
> I have also made sure "allow selection" was checked. Nothing I do at all will refresh with new API information. From my observation there appears to be something about being an admin .vs a developer that keeps them from refreshing. Is there a step or setting that I need to triple check to make sure the refresh happens as it should?
> 
> What's important for my client is that the API information dynamically regenerate. I have see the typescript code that calls out to
> `apis?expandApiVersionSet=true&$top=50&$skip=0&api-version=2018-06-01-preview `
> and the URL being called is exactly the same (including to the API M instance) but getting different results. I can only deduce that this is because of admin vs. developer mode.
> 
> Hope this information helps - I have spent two days on this issue now and hope I can get some insight.

In my case, it turns out I simply wasn't adding the APIs to my product.  So in admin mode it would show all APIs and in developer mode it would only show those subscribed which was only those related to my product.  Since this was not a bug, I will leave this here for anyone else that may make the same mistake.

**Comment by codebrane** [comment]
Updating the Function App that contains the API isn't reflected in the APIM that uses the Function App. I had to delete the APIs and re-import. Also Azure doesn't clean out Functions that no longer exist in a Function App so when re-importing to APIM I have to deslect Functions that no longer exist.
