### ISSUE TITLE
Publish Fail when delegation enabled - Unable to apply knockout bindings to a template: Error

### ISSUE THREAD

**Issue by lucaszacutti** [Azure/api-management-developer-portal#440]
npm run publish => Fail when signin delegation is enabled.
Message: Unable to apply knockout bindings to a template: Error
![error_message](https://user-images.githubusercontent.com/13422243/73208281-f4358e00-4124-11ea-9797-ae8a5804a1fe.jpeg)

See attached image for details and line causing error.
![code_failing](https://user-images.githubusercontent.com/13422243/73208328-0a434e80-4125-11ea-8a91-164b8a8f7260.jpeg)

**Comment by azaslonov** [comment]
Hi @lucaszacutti, thanks for reporting the issue. We'll fix this.

**Comment by lucaszacutti** [comment]
thanks Alexander, I think we have a fix, let me know if we could contribute it

**Comment by ndapolonia** [comment]
Hi everyone, 
I have the same error. Inspecting the code, I found the issue and I found the solution that allows me to publish the website.
Debugging the compiled code, i found that the error happens when the publish operation tries to get the delegation url calling the function
getDelegationUrl from the file src/service/backendService.ts 
and it can't read it because in the configuration file for publish "src/config.publish.json" there isn't a entry for the
backendUrl. So I took the backendUrl parameter from the "src/config.runtime.json" and now it works properly. However, I don't know if its correct to use the same backendUrl that is used
in "src/config.runtime.json", or this workaround is right.
Thanks

**Comment by ygrik** [comment]
@lucaszacutti you need to provide **backendUrl** setting in publisher config (src/config.publish.json)
If you enabled the delegation, the publisher should know where to get it.

@ndapolonia  the **backendUrl** setting is the same across publisher and runtime configs.

**Comment by lucaszacutti** [comment]
Ok, thanks Igor, now the problem is that when we do the callback to the developer portal with de /sigin-sso?token=...  we got an error 404, We are doing something wrong? thanks!

**Comment by ygrik** [comment]
@lucaszacutti could you submit this issue with details to Azure support
