### ISSUE TITLE
/signin-sso and /aadadminconsent  missing in new self-hosted developer portal

### ISSUE THREAD

**Issue by lucaszacutti** [Azure/api-management-developer-portal#445]
/signin-sso and /aadadminconsent  missing in new self-hosted developer portal

![image](https://user-images.githubusercontent.com/13422243/73385358-ce86c100-42ab-11ea-8562-23a63852f2d0.png)

without this feature we can't delegate signin because we can't callback portal with token in order to get logged on.

**Comment by azaslonov** [comment]
Hi @lucaszacutti, in the managed version of the APIM dev portal the delegation logic implemented on the portal backend. Since you're going self-hosted way, you, technically, don't need the delegation at all, you can just make it a part of the portal where you do authentication.

Regarding, `/aadadminconsent` - is about AAD integration, which is a different story, you don't need that for delegation.

Hope that answers your question. Please feel free to comment/re-open this issue shall you need further assistance.
