### ISSUE TITLE
Undo-Button not working while text-editor open

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#469]
## Bug description
When having the editor for text widgets open the "Undo"-button doesn't work properly.

## Reproduction steps

1. Go to 'Home'
2. Add a text-widget
3. Click into the widget and type something
4. Without closing the text-editor-widget press "Undo"
5. See error

## Expected behavior
Even while a widget is active the "Undo"-button reverts the last step. Here: remove the written text.

## Is your portal managed or self-hosted?
Managed

## Environment

 - Operating system: Windows 10 1809
 - Browser: Chrome
 - Version 79.0.3945.130

**Comment by azaslonov** [comment]
Hi ZarTrox, thanks for reporting the issue.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
