### ISSUE TITLE
New DevPortal - Highlighting of related main and sub menut items

### ISSUE THREAD

**Issue by AnRei123** [Azure/api-management-developer-portal#476]
## Bug description / reproduction steps

1. Click an menu item in the main menu in the header. The clicked main menu item is highlighted in bold font after the target page has been opened:
![Issue-Menu-highlighting](https://user-images.githubusercontent.com/58981351/74427299-1b939700-4e57-11ea-9975-88d974a6ae4b.JPG)

2. Click a sub menu item in the left navigation menu on the target page. The highlighting of the related main menu item disappears. All main menu item appear unbold:
![Issue-Menu-highlighting_missing-for-sub-menu-item](https://user-images.githubusercontent.com/58981351/74427312-21897800-4e57-11ea-9f49-12586e067aeb.JPG)

Thus, the user losts orientation / focus at which content of the main menu topic he/she is currently looking at.

## Expected behavior
When clicking a sub menu item on a page of a main menu, I can configure  that the highlighting status of the main menu shall still remain when navigating between the items of the sub menu.

## Is your portal managed or self-hosted?
Managed 

## Environment
 - Operating system: Windows 10
 - Browser: FireFox 68.4.2esr (32-bit)

**Comment by azaslonov** [comment]
Hi @AnRei123, thanks for reporting the issue. We'll fix that.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
