### ISSUE TITLE
OAuth Sign In Widget Redirects to Sign Up and Requires Email, But Won't Take Email

### ISSUE THREAD

**Issue by TravisLRiffle** [Azure/api-management-developer-portal#480]
#194  Bug description

Adding a AAD B2C OAuth SignIn widget associated to a SignIn/SignUp will redirect to another "Sign Up" page which expects email, first name and last name.  When entering the email that the user signed up with, it returns - Server error. Unable to send request. Please try again later.

When reviewing the network tab I see - theme.js:2 POST https://<APIMINSTANCE>.management.azure-api.net/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxxxx/providers/Microsoft.ApiManagement/service/<APIMINSTANCE>/users?api-version=2018-06-01-preview 400 (Bad Request)

In the network tab, I see {"error":{"code":"ValidationError","message":"One or more fields contain incorrect values:","details":[{"code":"IdentifierAlreadyInUse","target":"email","message":"User with specified identity already exists"}]}}

Since this information was already collected in the "sign up" process of the B2C page, why is it being collected again?  And if it's collected again, shouldn't it be okay that the email is the same or why does there need to be an email address at all? 
## Reproduction steps

Self-Host Portal
Add OAuth Widget 
Configure OAuth Widget and B2C
Click on Sign In
Sign Up -> Fill out fields, verify code, set PWs, etc.
Submit -> redirect to Sign Up Page which expects the same claims that were set in the previous sign up page.  

I've tried removing the Sign Up widgets altogether, but for some reason I still get redirected to this page.  

## Expected behavior

Once the user is created, it never even redirects to the Sign Up page.

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)
2.2.1

## Environment

 - Operating system: Windows
 - Browser: Google Chrome
 - Version: Latest

**Comment by azaslonov** [comment]
Hi Travis, the information required for sign up with AAD B2C and for creating APIM account are not necessarily the same, and even may not be part of the same flow, that's why we collect/confirm it for APIM account separately. Though, we may add an option "not to ask" for it in the future, provided that all the information available in id_token.

P.S: generic error message has been replaced with proper one in #482.

**Comment by TravisLRiffle** [comment]
> Hi Travis, the information required for sign up with AAD B2C and for creating APIM account are not necessarily the same, and even may not be part of the same flow, that's why we collect/confirm it for APIM account separately. Though, we may add an option "not to ask" for it in the future, provided that all the information available in id_token.
> 
> P.S: generic error message has been replaced with proper one in #482.

I appreciate the quick response - my question is, why can't I enter in the same email that I "signed up" with on the OAuth page on the APIM Account Sign Up page?

**Comment by azaslonov** [comment]
I believe that the user with the same email already exists (e.g. with user name/password account). Our system doesn't 2 authentication methods for the same user.

**Comment by TravisLRiffle** [comment]
Okay - so here's the experience.  I go the dev portal.  I sign up through B2C with myuser@gmail.com.  I am then thrown into the sign up screen - when I enter myuser@gmail.com, I get an error.  I've NEVER entered the user into APIM before and when I look at the console, the error is on that the user email already exists.  I think *that* is a bug.

**Comment by KellyBennett** [comment]
@azaslonov 
I understand that OP is using AAD B2C, but this problem is exactly the same in a non B2C AAD scenario. Please re-open this issue.

I have this very same issue in an in-house example where I want to use my company's organizational directory only.

Consider that I'm an employee at a company, and I'm using the developer portal to see our company's APIs, I try to sign in with my Azure Active Directory, and I'm told I need to "Complete sign up", so I enter my work email, and I'm STUCK. There is now no way to proceed to the documentation, because entering my work email shows the error `User with specified identity already exists`. This looks 100% like a broken login flow and I file a bug to some poor co-worker to fix it.

And what's the remedy?? That I the company requires employees to use _personal_ emails? 1) That's bonkers 2) That's causes huge friction because every one of the employees who signs up is going to have to be educated that the log in flow requires them to sign up with a personal email.

Is this truly the intended flow!?

**Comment by azaslonov** [comment]
@KellyBennett, first of users see "Complete sign up" screen only when there is missing information in `id_token`. Sign-up logic expects to see *email*, *first name* and *last name*; and, if it's all there, it just creates account without showing that screen.

When you enable AAD B2C and, at the same time, disable Basic authentication, the issue `User with specified identity already exists` should never come up.

Now if you want to support both B2C and Basic, it is OK, unless a single user doesn't try to register with the same email for both.

**Comment by KellyBennett** [comment]
@azaslonov ~Two days ago I was seeing this behavior with just AAD enabled (not AAD B2C), however I'm mysteriously not able to reproduce it anymore, and everything is working as you describe 🤷 

Login flow is working good now. 👍 

Thanks for the response!

**Comment by azaslonov** [comment]
Hi @KellyBennett, thanks for confirmation. I'm glad it worked out for you.

**Comment by pandeyr003** [comment]
Hi,

> @KellyBennett, first of users see "Complete sign up" screen only when there is missing information in `id_token`. Sign-up logic expects to see _email_, _first name_ and _last name_; and, if it's all there, it just creates account without showing that screen.
> 
> When you enable AAD B2C and, at the same time, disable Basic authentication, the issue `User with specified identity already exists` should never come up.
> 
> Now if you want to support both B2C and Basic, it is OK, unless a single user tries to register with the same email for both.
> 
> Hope this makes sense.

Hi

How to remove 'Complete Sign up' page? Once the AD is enabled, we want our AD users able to directly login to developer portal without entering details in 'Complete Sign up' page. This is urgent, would appreciate if anyone address my query earliest possible
