### ISSUE TITLE
Uploading an Imagine for Self-hosting fails with a 403

### ISSUE THREAD

**Issue by TravisLRiffle** [Azure/api-management-developer-portal#501]
## Bug description

When I run in localhost mode, I just want to reference an image.  I've tried the upload feature, but it fails with a 403.  I tried uploading in APIM and regenerating the content, but still get a 403.  

## Reproduction steps

1.  Run as localhost
2.  Attempt to upload an image for hosting
3.  Get error in console of a 403. 

## Expected behavior
Uploading an image should appear.  

## Is your portal managed or self-hosted?

Self-hosted

## Release tag or commit SHA (if using self-hosted version)

2.2.2

## Environment

Chrome (latest)

**Comment by azaslonov** [comment]
Hi @TravisLRiffle, that's a bit too broad question, but 403, in this case, means that the Storage connection string that you use doesn't allow to do "write" operations.

I'm closing the issue for now, because it is not a code defect, it's just a matter of permissions that you need to figure out.

![image](https://user-images.githubusercontent.com/2320302/75074879-752c3f00-54b1-11ea-8473-ff18ac3823da.png)
