### ISSUE TITLE
Copying & Moving Links not possible

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#515]
## Bug description
When trying to copy a linked text-element into another text box it creates an "oops" error message.

## Reproduction steps
1. Create 2 text sections
2. Mark part of one section as a Link
3. Copy the whole Link 
4. Paste it into the other section
5. Receive Error message

## Expected behavior
Links behave like normal text-elements and are able to be copied & moved.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Operating system: Windows 10
 - Browser: Chrome
 - Version: 80.0.3987.122

## Additional context

Without Links:
![DCB8EC8E-A22C-4093-A36F-0D4F5386A52D](https://user-images.githubusercontent.com/58420097/75526375-f6378900-5a11-11ea-92a9-a4e7e9f07fd7.GIF)

With Links:
![01E29778-6B68-43A4-9CA6-A705B594731E](https://user-images.githubusercontent.com/58420097/75526657-778f1b80-5a12-11ea-917f-1163191c3c42.GIF)

**Comment by azaslonov** [comment]
Hi @ZarTrox, thanks for reporting the issue. We'll fix that.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
