### ISSUE TITLE
Multiple people working on the same page will lose progress

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#557]
#  Bug description

When working with a coworker on the **same page**, saving this page will lose progress of the other one.

## Expected behavior

The portal allows one to work parallel on the same page (In different widgets) by taking into account changes of multiple people.
Or it generates a message, that the saves won't be taken into account.

## Is your portal managed or self-hosted?

Managed

## Environment

 - Browser: Chrome Version 80.0.3987.149

## Additional context

This error occurred while editing a widget my coworker wasn't. Saving worked for me but after restarting the portal my progress has been lost. (It worked after my coworker logged out and waited until I finished)

**Comment by mikebudzynski** [comment]
We'll make sure the limitation is documented. If you'd like to work in parallel, a DevOps process is the best approach.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
