### ISSUE TITLE
Try It - Template parameters turn into query string parameters

### ISSUE THREAD

**Issue by DavidFreetly** [Azure/api-management-developer-portal#582]
## Bug description

When I use the 'Try It' feature on an operation with a template parameter it seems to be getting added to the request URL as a query string parameter instead of adjusting the URL appropriately.

## Reproduction steps

1. Use an API with template parameters defined for the operations.  The Conference API is a good example.
2. Click on an operation that uses a template parameter.  GetSession is a good example.
2. Click on the 'Try it' button
3. Enter a value for the template parameter.
4. Notice in the 'HTTP request' section that the URL now has a query string parameter at the end of the URL.

## Expected behavior

The URL in the 'HTTP request' section should include the template parameter in the URL and not as a query string parameter.

## Is your portal managed or self-hosted?

Managed 
## Environment

 - Operating system: iOS
 - Browser: Google Chrome
 - Version: 81.0.4044.113

## Additional context

<img width="601" alt="Screen Shot 2020-04-17 at 7 20 35 AM" src="https://user-images.githubusercontent.com/4295769/79570964-fa7e3b00-807f-11ea-8cb1-4c02ebbab863.png">

![Screen Shot 2020-04-17 at 7 21 13 AM](https://user-images.githubusercontent.com/4295769/79571001-07029380-8080-11ea-9385-9c9911f10884.png)

**Comment by azaslonov** [comment]
Hi David, yes I could repro. Thank you for reporting the issue, we'll fix it.

**Comment by azaslonov** [comment]
ETA for this issue ETA 5/29, unless someone wishes to contribute.

**Comment by azaslonov** [comment]
@DavidFreetly, the issue has been fixed. Please pull the latest bits to pick it up. The release for the managed version is in progress and should be complete by the end of next week.

**Comment by DavidFreetly** [comment]
@azaslonov, Thank you!

**Comment by nahojs** [comment]
Same result when using a wildcard template parameter. For example GET `/something/{*url}`. 

Expected behavior same as OP _"The URL in the 'HTTP request' section should include the template parameter in the URL and not as a query string parameter."_

When using "Try-it" in the Dev-portal the result is a **500 Internal Server Error**, but works when using Curl v7.55.1 (Windows)

`curl -X GET -H "Ocp-Apim-Subscription-Key: xxx" "https://example.com/t/https://www.google.com"`

Image from "Try-it"
![Capture](https://user-images.githubusercontent.com/84910655/120711922-411b3880-c4c0-11eb-81dd-dbee3de783f2.jpg)

**Comment by mikebudzynski** [comment]
@nahojs, the original problem has been fixed and this issue has been already closed. Could you create a new one with precise reproduction steps?
