### ISSUE TITLE
Possible to replace default developer portal UI with Swagger UI?

### ISSUE THREAD

**Issue by IanKemp** [Azure/api-management-developer-portal#607]
[Swagger UI](https://swagger.io/tools/swagger-ui/) is the industry standard for OpenAPI (formerly Swagger) web APIs. It's extremely common and most web developers will recognise it immediately.

This is in contrast to the Azure API Management developer portal UI, which is laid out quite differently to Swagger UI, is more complicated to use, buggier, and in general a completely different experience.

As such, it would be highly desirable to be able to use Swagger UI **in place of** the current developer UI, particularly when exposing OpenAPI endpoints.

1. Is this a supported scenario?
2. If not, is this something that Microsoft would be interested in adding?
3. If not, could you at least provide hooks so that people can build their own API user interfaces, instead of being forced to use the current Microsoft-provided UI?

**Comment by azaslonov** [comment]
Hi @IanKemp, you're right Swagger UI is a great tool. Regarding your questions:
1. Since this is an open-source project, Swagger UI extension could be added as a run-time widget for this portal. It could be placed on a page instead of, let's say, operation details widget. So, I can easily see that.
2. Sure, community contributions are always welcomed.
3. All the extension points are already there. If you're interested, please follow [this tutorial](https://github.com/Azure/api-management-developer-portal/wiki/Implement-widgets), it should give you a pretty good idea how to implement it.

Of course, you can count on our full support with your contributions.
