### ISSUE TITLE
Mandatory query parameters shown as template type 

### ISSUE THREAD

**Issue by watson20201** [Azure/api-management-developer-portal#636]
When setting a query parameter as "required:true" in the schema specification as shown below:

![image](https://user-images.githubusercontent.com/62035456/82764919-a88eb900-9e66-11ea-8b67-3ebf9e32108a.png)

It is shown as a template type when viewed in the portal as shown here:

![image](https://user-images.githubusercontent.com/62035456/82764955-edb2eb00-9e66-11ea-876f-cb1202e48596.png)

Instead it should be displayed as a query type.

**Comment by azaslonov** [comment]
Hi @watson20201. This issue has been fixed. The release is in progress.

**Comment by Kumar-Ashwin-Hubert** [comment]
This bug needs to reopened as the issue has reoccurred.

Setting a required `"Query"` parameter in OpenAPI is getting set as `"Template"` parameter. 

### Detailed Info:

In the below OpenAPI sample, `id` has been marked as a required parameter in query : 
![image](https://user-images.githubusercontent.com/25590394/114359107-44193d00-9b91-11eb-8e2b-1b47d98454cd.png)

On save of the OpenAPI spec, the mandatory query param is getting mapped to template param.

![image](https://user-images.githubusercontent.com/25590394/114359680-da4d6300-9b91-11eb-95cf-3f2b34422878.png)

The main issue is that if the end user doesn't provide an `id` in this above example, they would get a 404 resource not found without any additional info instead of a 400 Bad Request.

**Comment by cemusta** [comment]
I'm having this problem as well

**Comment by malincrist** [comment]
Hello, this issue doesn't seem to be specific to developer portal.
Please contact Azure support for assistance.

**Comment by cemusta** [comment]
> Hello, this issue doesn't seem to be specific to the developer portal. Please contact Azure support for assistance.

sorry, noticed it's actually happening on terraform. API import doesn't have this problem.

**Comment by pradeepkottalage** [comment]
you can mark required = false and add validation for that
