### ISSUE TITLE
Getting "Required params not found" error while resetting password for invited users

### ISSUE THREAD

**Issue by dhandapanitrimble** [Azure/api-management-developer-portal#687]
Steps to Recreate:
1. Invite users from the Admin portal
2. Click on the confirmation link from users email invitation mail
3. It is navigating to the Reset Password page. Expecting this page should not throw any error.
But its throwing "Required params not found" error.
4. Enter the password and confirm password
5.Getting "Server error. Unable to send request. Please try again later."
Due to this issue not able to proceed with invite users functionality.

**Comment by mhgames** [comment]
I confirm this behaviour, initially I thought this was an issue of my newly published developer portal (in my production subscription), but I've just tried that in my already existing developer portal (which has many active users from the past) and the result is the same as OP is describing.

**Comment by Harjindar** [comment]
I confirm this too. It is for existing as well as new instances. Our new customers (API user) are confronted with error after being invited on our API platform.

**Comment by spyder007** [comment]
I'm noticing this error in the developer console:
`Script from https://{custom-portal-domain}/scripts/vendor.js was blocked due to mime type mismatch`

And then this error when trying to request a reset:
`[object Error]: {description: "Unable to get property 'dispatchEvent' of undefined or null reference", message: "Unable to get property 'dispatchEvent' of undefined or null reference", number: -2146823281, stack: "TypeError: Unable to get property 'dispatchEvent' of undefined or null reference at Anonymous function (https://{custom-portal-domain}/scripts/theme.js:2:2180539) at Generator.prototype.next (native code) at Anonymous function (https://{custom-portal-domain}/scripts/theme.js:2:2177817) at PromiseConstructor (https://{custom-portal-domain}/scripts/theme.js:2:1257107) at Anonymous function (https://{custom-portal-domain}/scripts/theme.js:2:2177428) at prototype.resetSubmit (https://{custom-portal-domain}/scripts/theme.js:2:2178897) at Anonymous function (https://{custom-portal-domain}/scripts/theme.js:2:135076) at h (https://{custom-portal-domain}/scripts/theme.js:2:1185420)"}
description: "Unable to get property 'dispatchEvent' of undefined or null reference"
message: "Unable to get property 'dispatchEvent' of undefined or null reference"
number: -2146823281
stack: "TypeError: Unable to get property 'dispatchEvent' of undefined or null reference at Anonymous function (https://{custom-portal-domain}/scripts/theme.js:2:2180539) at Generator.prototype.next (native code) at Anonymous function (https://{custom-portal-domain}/scripts/theme.js:2:2177817) at PromiseConstructor (https://{custom-portal-domain}/scripts/theme.js:2:1257107) at Anonymous function (https://{custom-portal-domain}/scripts/theme.js:2:2177428) at prototype.resetSubmit (https://{custom-portal-domain}/scripts/theme.js:2:2178897) at Anonymous function (https://{custom-portal-domain}/scripts/theme.js:2:135076) at h (https://{custom-portal-domain}/scripts/theme.js:2:1185420)"

__proto__: Error`

**Comment by mikebudzynski** [comment]
The fix is already implemented, but it requires the API Management service release to fully roll out. ETA is around the end of July.

@spyder007 Your issue is going to be resolved in a few days, when the developer portal release rolls out.
