### ISSUE TITLE
email sent by the portal are all redirecting to the old APIM dev portal

### ISSUE THREAD

**Issue by poshgrad** [Azure/api-management-developer-portal#764]
Good afternoon, 

I have come to an issue with the "Developer welcome letter".
The repoduction steps are pretty simple; you register to the APIM dev portal and you will receive a welcome letter similar to the one in attachment (in the case of our portal, the redirect URL is :
- _OLD PORTAL https://portal-dev.thuasne.com/products/thausne-customers_  when it should be 
- NEW PORTAL https://developer-dev.thuasne.com/
Problem is we don't use the old portal so all those links provided to my subscribers are wrong.

It seems that it can be replaced manually in the HTML through the Notifications templates in the Publisher portal. 
But to do the job properly we would need to be able to change the referenced value for the Developer portal "Developer Portal URL".

Can you please tell me how to do so ?  Where do I find the referenced file?

BR

Julien

**Comment by ygrik** [comment]
Hello @poshgrad 

We are working on this issue with the $DevPortalUrl template variable. 
The fix will be with an upcoming release.

**Comment by poshgrad** [comment]
Perfect. Thank you.

**Comment by mikebudzynski** [comment]
The fix for this issue will be included in the next API Management release. Please, check again in around 3 weeks, after republishing your portal.

**Comment by VWACBrick** [comment]
@mikebudzynski , our site is self-hosted and Publish action is disabled because of our configuration. Do we have to do something else now to get this change to our site?

![image](https://user-images.githubusercontent.com/65634611/91083486-3a8d9580-e5ff-11ea-95d2-8e40fe197145.png)


Do we use the Azure CLI?
https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/publish-azapimanagementtenantgitconfiguration?view=azps-4.5.0
