### ISSUE TITLE
Unable to sign out in managed developer portal properly 

### ISSUE THREAD

**Issue by Gowtham2371998** [Azure/api-management-developer-portal#768]
Hi Team

Description:
Sign out is not working properly in the managed developer portal, Help me out!

Steps to reproduce:
1.Signin -> APIs Page -> APIs Details Page ->Signout
2.Signin -> Products Page -> Product Details Page ->Signout

Actual:
Without Signout the user, it navigates to the home page or it will throw "404 HTTP error".

Expected:  
Should Signout the user and navigate to home page

Additional content:
This error is thrown when the above issue is happening

![Signout issue](https://user-images.githubusercontent.com/64083124/88046458-bf534280-cb6d-11ea-831b-20826b87d943.PNG)

![Signout issue1](https://user-images.githubusercontent.com/64083124/88046540-da25b700-cb6d-11ea-9cb5-cf319211cb28.PNG)

![Signout issue2](https://user-images.githubusercontent.com/64083124/88046549-ddb93e00-cb6d-11ea-875b-cbda4b9695be.PNG)

Thanks,
Gowtham.S

**Comment by ygrik** [comment]
Hi @Gowtham2371998 
This 401 is normal, because after SignOut on page load we try to check is auth cookie exists or not.
I can't reproduce your issue on my service. 
Could you please provide more details about the issue, send traces from browser and your service name on apimportalfeedback@microsoft.com or create support ticket against Azure API Management service.

**Comment by krishjag** [comment]
Hello @ygrik,

I ran into the same issue detailed above. I looked at the route guard below and traced it to the client side script.
**src/routing/signOutRouteGuard.ts**

The sign out function is setting the location.assign(url) to "/signout" and the redirection does not work because the resource /signout does not really exist. This issue might have started fairly recently.

![image](https://user-images.githubusercontent.com/24848674/89854525-198a6680-db62-11ea-8135-41d20fd44502.png)

![image](https://user-images.githubusercontent.com/24848674/89854748-b5b46d80-db62-11ea-9d8f-b82d59e882f9.png)

Thanks,
Jags
