### ISSUE TITLE
Subscription: No proper error message when limit is reached and a approval is pending

### ISSUE THREAD

**Issue by ilspiert** [Azure/api-management-developer-portal#791]
## Bug description

No proper error message is displayed when the subscription limit is reached and a approval is pending.

## Reproduction steps

1. Define a Product with a Subscription limit equals 1 and requires an approval
2. Start the new Developer Portal
3. Go to Products, select Subscription from step one and request an Subscription
4. Request right away the same Subscription again

## Expected behavior

Instead of nothing happen, an appropiate message should be shown, that a subscription request is pending and the limit is on X. 

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

2.4.1

## Environment

 - Operating system: Windows 10
 - Browser: Edge, Safari
 - Version: latest

**Comment by azaslonov** [comment]
Hi @fsettele, thanks for reporting the issue, we'll fix this.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
