### ISSUE TITLE
CSP content-security-policy headers missing

### ISSUE THREAD

**Issue by MayankBargali-MSFT** [Azure/api-management-developer-portal#798]
When navigating to developer portal (https://<apiminstancename>.developer.azure-api.net/) we observe that the security scanner is complaining that developer portal page has no CSP content-security-policy headers and are missing in response.

Can you look into it and if there us any way these CSP headers can be controlled?

**Comment by azaslonov** [comment]
Hi @MayankBargali-MSFT, no ETA at the moment, but this is a planned feature.

**Comment by azaslonov** [comment]
@MayankBargali-MSFT, is this important to you to specify type of resource in CSP (like `script-src` or `img-src`) or generic fallback `default-src` would be sufficient?

**Comment by Ledger94** [comment]
Hi @azaslonov, this feature will be very useful on the project, I'm working on as well. Is this feature's implementation currently being working on at this time? If so is there an ETA?

**Comment by azaslonov** [comment]
Hi @Ledger94, yes, this feature is in development right now. It's hard to say ETA at the moment, roughly it'll be mid-November for managed version because it requires backend deployment. For self-hosted version, however, metatag-based implementation should come much earlier: `<meta http-equiv="Content-Security-Policy"  content="default-src 'self'">`.

Btw, I have same question to you: is this important to you to specify type of resource in CSP (like `script-src` or `img-src`) or generic fallback `default-src` would be sufficient?

**Comment by Ledger94** [comment]
If it is easier / less time consuming. It would be better to implement a generic solution first so that sooner rather that later user's can take advantage of CSP to make their Portal website more secure. Then perhaps in the future after some feedback is provided it can be expanded to the full CSP specifications. This is however just my personal opinion but, I appreciate the transparency from your end @azaslonov .

**Comment by narla-vinil** [comment]
Hi @azaslonov : We have a similar request from our Security team for adding CSP header to our developer portal instance. I would like to know the ETA for this issue. Thank You.

**Comment by mikebudzynski** [comment]
We are working on this improvement now. It will roll out with the main API Management service release in March or April.

**Comment by azaslonov** [comment]
CSP configuration features is being rolled out. ETA around 3 weeks.

**Comment by azaslonov** [comment]
The CSP UI is out:

![image](https://user-images.githubusercontent.com/2320302/174389187-0377b23f-aa4d-45ae-aee8-a7181a1ce274.png)

**Comment by khatrisalah** [comment]
Hi,

What is the allowed resources option, what needs to be add there, can we say that browser will block all resources unless it is mentioned in the allowed resources. Please help.

Thanks
