### ISSUE TITLE
Add adjustable timeout timer

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#807]
## Request description

The time until timeout (automatic log-out) is for many use cases to low.
Therefore the timeout should either be configurable individually via the APIM portal or a timeout happens not earlier than after 30 minutes.

## Is your portal managed or self-hosted?

Managed

## Additional context

This Problem has already been mentioned in #806 but it deserves an own issue.
Also #507 depicts this Problem.

**Comment by ZarTrox** [comment]
The time until log-out seems to be around 5 minutes.

**Comment by azaslonov** [comment]
Hi @ZarTrox, thanks for suggestion, we'll see what we can do.

**Comment by AnRei123** [comment]
The **timeout period** for the editor mode of the DevPortal is still much TOO SHORT. It is about less then 15 minutes. It should be at least 30 minutes. And since this week, after timeout, modified data cannot be saved anymore. So **I lost my data** two  times this week due to a timeout! These two issues had already been fixed and do appear again now. It is not possible to efficiently work with these complaints in the new DevPortal.

**Comment by mikebudzynski** [comment]
@AnRei123 Apologies for inconvenience. It is not a regression, the administrative token refresh has never been implemented. We will prioritize this issue.

**Comment by mikebudzynski** [comment]
Closed with token auto-refresh: https://github.com/Azure/api-management-developer-portal/commit/e7da437560603331c38ce9075f05458e1c6a4cb8 The release was rolled out in January.
