### ISSUE TITLE
Enable Multi-/two-factor-authorization for published portal via web URL ADD button

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#847]
## Bug description

The AAD-Sign-in button of the published dev portal shall also support two-factor-authorization.
For our developer personal accounts with dedicated security rights logs into the published portal a two-factor-authorization is required. When clicking the AAD button on the published dev portal, for example, they enter their AAD user name and get asked for a code that had been sent as a SMS to their mobile phone. After entering the code in the AAD authentication window, they remain on the sign-in page. The portal home page does not open – even if they refresh the browser nothing happens.

## Expected behavior

When a user logs-in to the published DevPortal with two-factor-authorization, the home page of the portal environment opens without any issues.

## Additional context

Until this problem is resolved the legacy DevPortal must not be deprecated or the link to the legacy portal may not be removed from the APIM portal.

## Is your portal managed or self-hosted?

Managed

**Comment by azaslonov** [comment]
Hi @ZarTrox, we'll investigate and fix. Thank you.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
