### ISSUE TITLE
Automatically detect and remove data corpses

### ISSUE THREAD

**Issue by ZarTrox** [Azure/api-management-developer-portal#867]
## Bug description

Today I noticed when editing the DevPortal that in a navigation menu there was "empty space". When hovering over it I noticed that there was an empty/non-exsistent navigation item which was not displayed in the navigation panel (the bar on the left). After further research I found that an empty item is in the data.json file (see screenshot)
![DataCorpses](https://user-images.githubusercontent.com/58420097/91827036-a2b32b80-ec3e-11ea-8d6a-d4efc763a01a.png)

After removing this block it works perfectly fine.
But if this could resurface an automatism in place which could detect those corpses and at least send out a notification would be necessary for a clean Portal with no unexpected issue which can't be quickly detected.

## Reproduction steps

Unfortunately I can't reproduce how this data corpse got created.

## Expected behavior

When such an empty element is present in the DevPortal it should automatically detect such elements and send out a notification before saving/publishing or deleting if it is clear that this is not supposed to be present.

## Is your portal managed or self-hosted?

Managed

**Comment by AnRei123** [comment]
The expected behavior should be to remove such items completely from the data.json if the item is not reflected anymore in the navigation editor panel. The effect of this corpse was that in the published portal menu the distance between two navigation entries was too large. But in the edit mode of the portal it was not possible to fix the issue, only in the data.json. Such issues should be covered by the portal backend already w/o any user action.

**Comment by azaslonov** [comment]
Indeed. Thanks for reporting this, we'll add validation to the form and prevent it from rendering as well.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
