### ISSUE TITLE
Pictures not migrated

### ISSUE THREAD

**Issue by nmeuret-smag** [Azure/api-management-developer-portal#868]
## Bug description

Migrate.js script run, no error displayed but all source pictures are missing on target portal (migrate.js from scripts.v2 forlder)

## Reproduction steps

1. Run scripts.v2/migrate.js script
2. Go to target portal
3. Pictures media contents are missing

## Expected behavior

Picture should be migrated 

## Is your portal managed or self-hosted?

Managed

## Release tag or commit SHA (if using self-hosted version)

[e.g., release `2.0.0`, commit `c45da9778b70d369aba60fa2e63c191efe2b548f`]

## API Management service name

TEST-NMT-APIM

## Environment

 - Operating system: Windows 10
 - Browser: Chrome
 - Version: 80

## Additional context

Script launched both from Windows and Ubuntu

**Comment by azaslonov** [comment]
Hi @nmeuret-smag, v2 version of scrips if for upcoming service changes. It should be out in the next 2 days. We published it now because service upgrade happens region by region, so that both upgraded and non-upgraded customers could use the scripts. Just please wait a bit before you can start using it.

**Comment by nmeuret-smag** [comment]
Thanks, I will wait for V2.
