### ISSUE TITLE
No error state for non-existent APIs

### ISSUE THREAD

**Issue by mikebudzynski** [Azure/api-management-developer-portal#972]
## Bug description

A clear and concise description of the bug.

## Reproduction steps

1. Go to API reference page URL, which points to non-existent API.
2. Interface doesn't stop to load and doesn't show any error.

## Expected behavior

Visitor should be notified that the API doesn't exist. The interface shouldn't continue to load indefinitely.

## Is your portal managed or self-hosted?

Managed

![image](https://user-images.githubusercontent.com/40186513/96043280-8d2b4700-0e23-11eb-976e-a26746c3e02c.png)

**Comment by mikebudzynski** [comment]
Fixed with the PR linked above and included in the releases 2.5.2.

**Comment by mrcarlosdev** [comment]
This issue is related to managed developer portal. We advise you to create a Azure support request to get assistance on this issue. Please refer to the below link to create a new Azure support request, Please select Problem Type = "Developer Portal" in the request to route it appropriately.

https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
