### ISSUE TITLE
The request header field is not shown in the front end of the Developer Portal

### ISSUE THREAD

**Issue by AdeZwart** [Azure/api-management-developer-portal#980]
## Bug description

The request header field is not shown in the front end of the Developer Portal

## Reproduction steps

1. Add the following json to an API resource in the ARM template:
`        "request": {
          "queryParameters": [],
          "headers": [
            {
              "name": "Authorization",
              "description": "Contains the bearer token for authorization. The token must be prefixed with Bearer and a whitespace.",
              "type": "string",
              "required": true,
              "values": [],
              "defaultValue": "Bearer "
            }
          ],
          "representations": []
        }`

2. Deploy the ARM template
3. Open the API in the Portal
4. Verify the Authorization header is there:
![image](https://user-images.githubusercontent.com/8612100/96548832-d7db1200-12ae-11eb-8260-638433f89de8.png)
5. Publish the Developer Portal 
6. Browse to the "Try It" function of the endpoint
7. See that the Authorization header field is not shown with the "default value" preset.
![2020-10-20_08h39_20](https://user-images.githubusercontent.com/8612100/96549473-d1996580-12af-11eb-9bd0-29795bea907c.png)

## Expected behavior
The authorization header field is shown with the "default value" set in the field.
![2020-10-20_08h40_14](https://user-images.githubusercontent.com/8612100/96549544-e970e980-12af-11eb-9c7e-a2b506ceda75.png)

**Comment by renafly** [comment]
Same happens to me :S

**Comment by dvdhoopevident** [comment]
We have multiple APIM resources in Azure and currently, some of them show this bug and others don't. I don't exactly know how to compare the developer portal versions, but if I compare the publish dates:

- APIM resource **without** this bug: Last published on 4-8-2020 18:04:04 (4th of August)
- APIM resource _with_ this bug: Last published on 7-10-2020 11:03:03 (7th of October)

The APIM resource without this bug also shows: "Your published portal’s version isn’t up-to-date. Publish the portal to automatically upgrade it to the latest version, which contains improvements and bug fixes.".
![image](https://user-images.githubusercontent.com/16252649/96562399-03ff8e80-12c1-11eb-9249-9b519ef28d8d.png)

So my guess is, that this bug was introduced by a release somewhere between the 4th of August and the 7th of October.

Hope this helps narrow down the issue.
